### ISSUE TITLE
Event source gets closed due to HTTP 504 (Gateway Time-out)

### ISSUE THREAD

**Issue by SachinSPawar** [stellar/java-stellar-sdk#104]
I am using TransactionRequestBuilder to get a stream of transaction created for a Stellar account. This works for sometime , then after sometime I don't get any events for the account even if I do new transactions. Instead, I get error HTTP 504 Gateway Timeout.

Please refer to the following screenshot:

![image](https://user-images.githubusercontent.com/10770626/41079583-f70a75e0-6a3f-11e8-8cbf-4efa044344c5.png)

Is there anything that I am missing?

Thanks for help in advance.

**Comment by elucidsoft** [comment]
This happens due to load balancer on Horizon. In the .NET SDK we
automatically reconnect, this can also be problematic however if you need
to resume where you left off when the disconnect occurs. One way to resolve
this is to host your own server and connect to that instead of the public
one.

**Comment by SachinSPawar** [comment]
This issue occurs even on mainnet horizon server. 
![image](https://user-images.githubusercontent.com/10770626/46602544-25dcad00-cb0e-11e8-924e-ba406919792a.png)

**Comment by bartekn** [comment]
The next version of horizon will send heartbeat in SSE streams so this should be fixed. Also, we should get rid of Jersey, check #141.

**Comment by overcat** [comment]
Due to the long period of inactivity on this issue, I have decided to close it. If there are any more problems, please don't hesitate to reopen it.
