### ISSUE TITLE
Time out

### ISSUE THREAD

**Issue by prettyCoders** [stellar/java-stellar-sdk#113]
When i send coin use java-stellar-sdk,My  node show me "time out",But the transaction is valid.
help please.

![qq 20180717164648](https://user-images.githubusercontent.com/36216120/42806541-4453b88c-89e1-11e8-913f-13ab46933476.png)

**Comment by prettyCoders** [comment]
I need it give me the transaction hash

**Comment by bartekn** [comment]
In case of timeouts you should resubmit the same Transaction Envelope XDR (without any changes) again to read it's status. Please check: https://www.stellar.org/developers/horizon/reference/endpoints/transactions-create.html#timeout
