### ISSUE TITLE
classpath issues with Spring Boot 2.x

### ISSUE THREAD

**Issue by jillesvangurp** [stellar/java-stellar-sdk#122]
I've been trying to use the api client in a Spring Boot project. One of the transitive dependencies is pulling in some old version of javax.validator, which is causing a lot of problems with spring boot auto configuration. So I looked at the transitive dependencies and it seems to pull in a lot of stuff, most of which is pretty out of date. 

```
com.github.Stellar:java-stellar-sdk:0.3.0

     com.squareup.okhttp3:okhttp:3.9.1
     com.moandjiezana.toml:toml4j:0.5.1
         com.google.code.gson:gson:2.3.1 ➡ 2.8.5
     org.mockito:mockito-core:2.13.0 ➡ 2.15.0
         net.bytebuddy:byte-buddy:1.7.9 ➡ 1.7.11
         net.bytebuddy:byte-buddy-agent:1.7.9 ➡ 1.7.11
         org.objenesis:objenesis:2.6
     com.google.guava:guava:18.0
     com.google.code.gson:gson:2.4 ➡ 2.8.5
     commons-io:commons-io:2.4
     org.glassfish.jersey.core:jersey-client:2.22.1 ➡ 2.26
         javax.ws.rs:javax.ws.rs-api:2.1
         org.glassfish.jersey.core:jersey-common:2.26
             javax.ws.rs:javax.ws.rs-api:2.1
             javax.annotation:javax.annotation-api:1.2 ➡ 1.3.2
             org.glassfish.hk2.external:javax.inject:2.5.0-b42
             org.glassfish.hk2:osgi-resource-locator:1.0.1
         org.glassfish.hk2.external:javax.inject:2.5.0-b42
     org.glassfish.jersey.media:jersey-media-sse:2.22.1
         org.glassfish.hkject:2.4.0-b31 ➡ 2.5.0-b42
         org.glassfish.jersey.core:jersey-server:2.22.1 ➡ 2.26
             org.glassfish.jersey.core:jersey-common:2.26
             org.glassfish.jersey.core:jersey-client:2.26
             javax.ws.rs:javax.ws.rs-api:2.1
             org.glassfish.jersey.media:jersey-media-jaxb:2.26
                 org.glassfish.jersey.core:jersey-common:2.26
                 org.glassfish.hk2.external:javax.inject:2.5.0-b42
                 org.glassfish.hk2:osgi-resource-locator:1.0.1
             javax.annotation:javax.annotation-api:1.2 ➡ 1.3.2
             org.glassfish.hk2.external:javax.inject:2.5.0-b42
```
IMHO e.g. mockito has no business being on the compile classpath. I suspect most of that jersey stuff is a combination of obsolete (glassfish project was made independent by Oracle) and all sorts of trouble in combination with Spring Boot. If you can, please just get rid of jersey entirely or at least exclude all the stuff you definitely don't need in an api client, like the server stuff.

You might want to use these two plugins to update the dependencies to the latest versions. I've had good success with using this on my own projects
```
apply plugin: 'project-report' // useful for gradle htmlDependencyReport
apply plugin: 'com.github.ben-manes.versions' // gradle dependencyUpdates -Drevision=release
```
You might also want to consider shading these dependencies and reconsider what is really essential here. That will reduce the amount of trouble your dependencies cause for your users.

Unfortunately this is blocking me in my evaluation of stellar. I'm planning to write my own simple client around OK Httpclient for those things I need.

**Comment by bartekn** [comment]
Fixed in #123.
