### ISSUE TITLE
Unable to get a source asset from PathPaymentOperationResponse 

### ISSUE THREAD

**Issue by parkhomenko** [stellar/java-stellar-sdk#125]
It is not possible to retrieve a **source asset** in the PathPaymentOperationResponse class due to a bug in the code.
Below is the code snippet from that class:
```java
    public Asset getAsset() {
        if (this.assetType.equals("native")) {
            return new AssetTypeNative();
        } else {
            KeyPair issuer = KeyPair.fromAccountId(this.assetIssuer);
            return Asset.createNonNativeAsset(this.assetCode, issuer);
        }
    }

    public Asset getSourceAsset() {
        if (this.sourceAssetCode.equals("native")) {
            return new AssetTypeNative();
        } else {
            KeyPair issuer = KeyPair.fromAccountId(this.sourceAssetIssuer);
            return Asset.createNonNativeAsset(this.sourceAssetCode, issuer);
        }
    }
```

There are two public methods **getAsset()** and **getSourceAsset()** in that class, which serve for getting an asset object. It is impossible to get the last one because of the incorrect **if** check in it:
```java
if (this.sourceAssetCode.equals("native")) {
```
It checks for the **asset code** instead of the type for the **source asset**.
The code should probably be changed to (the same way as in the **getAsset()** method):
```java
if (this.sourceAssetType.equals("native")) {
```

**Comment by bartekn** [comment]
Are you sure? `Asset.getSourceAsset` doesn't check any `asset` fields.

**Comment by bartekn** [comment]
OK, I see it now, thanks!
