### ISSUE TITLE
Exception during the getting a single operation

### ISSUE THREAD

**Issue by parkhomenko** [stellar/java-stellar-sdk#137]
There is a small mistake in the **org.stellar.sdk.requests.OperationsRequestBuilder** class in the next method:
```
public OperationResponse operation(long operationId) throws IOException {
    this.setSegments(new String[]{"operation", String.valueOf(operationId)});
    return this.operation(this.buildUri());
}
```
Instead of **operation** should be **operations** (plural).

Here is the exact link:
https://github.com/stellar/java-stellar-sdk/blob/master/src/main/java/org/stellar/sdk/requests/OperationsRequestBuilder.java#L54

**Comment by bartekn** [comment]
This method is getting a single operation so the singular form is OK.
