### ISSUE TITLE
return type of execute() in PaymentRequestBuilder.execute()

### ISSUE THREAD

**Issue by quanEmurgoVN** [stellar/java-stellar-sdk#138]
In this class: https://github.com/stellar/java-stellar-sdk/blob/master/src/main/java/org/stellar/sdk/requests/PaymentsRequestBuilder.java

I think execute() should return Page<PaymentOperationResponse>, yes?

**Comment by bartekn** [comment]
It returns `Page`. Please ask questions at [Stellar Stack Exchange](https://stellar.stackexchange.com/).
