### ISSUE TITLE
streaming apis are currently broken

### ISSUE THREAD

**Issue by jillesvangurp** [stellar/java-stellar-sdk#141]
I did some digging yesterday to figure out why the streaming APIs are not working currently in with the java sdk.

I discovered with a debugger that jersey is throwing an IllegalStateException stating that InjectionManagerFactory cannot be found. This gets caught inside jersey and results in the connection being closed right away after opening it. Events never make it to the event listener

This may be related to the shaded and relocated jar that was introduced. The class exists but has a different package name because of this. Somehow it does not pick it up and it fails without any log messages or visible exceptions. . 

In general, Jersey is doing all sorts of nasty things with reflection, bundling its own dependency injection framework, and pulling in all sorts of crazy  dependencies that are guaranteed to be a headache with e.g. Spring Boot.  I also think this is a bad idea on Android. This is the reason why I did #123; this avoids these conflicts.

A good long term solution would be to get rid of Jersey and instead built a simple solution around okhttp with minimal dependencies. There's absolutely no need to use jersey and IMHO using it should be avoided for client usage. I think it's primary use case is integration tests. 

I imagine this would be doable with in a day or so. Most of the API seems to be doing simple GETs and picking apart the responses with gson (just like is done right now). I think the only POST api is probably the submit transaction one. That too should be straightforward to do. You can do that in couple of lines of code with httpclient. 

Streaming is a bit more work, mainly because you need a background thread that keeps on reading the response and reconnects when needed. But that too is simple using an executor and the existing callback interface. This is basically what Jersey does as well but in a very convoluted way. Aside from that, all you need to do is add a single http header to trigger SSE on the server and a simple parser that picks apart the lines with the events.

There are a couple of short term workarounds. 1) do polling with the non streaming API. 2) reimplement just the streaming endpoints around okhttp as described above. Basically, should not be that hard to do as SSE is a very straightforward protocol. 3) roll back the shading for now and break compatibility with Spring boot 2.x (cannot have jersey on the classpath because of conflicting dependencies).

I'm willing to help on this of course but given how busy you guys are currently and the slow progress on my other PRs I would like to discuss upfront whether this is desirable/welcome now. I'm happy to continue using my fork for now. I implemented a workaround in my kotlin library based on polling that works well enough (Kotlin sequences and coroutines are very nice for this).

**Comment by bartekn** [comment]
OK, I think it's time to get rid of Jersey dependency. I think we should build a solution using okhttp, implementing SSE shouldn't be hard but there are a few corner cases we need to make sure I working as described in the specification:
* Client should reconnect when connection is reset (connection can be reset by ELB, etc.).
* Client should ensure that last event is processed when connection is finished ([Interpreting an event stream](https://www.w3.org/TR/2009/WD-eventsource-20090421/) section).
* Full specification can be found here: https://www.w3.org/TR/2009/WD-eventsource-20090421/

I think Golang implementation we have here: https://github.com/stellar/go/blob/master/clients/horizon/client.go#L351 is pretty good.

Let me know if you want to work on this.

**Comment by jillesvangurp** [comment]
Ok. I'm currently traveling. I may have a go at this when I'm back after
next week.

**Comment by bartekn** [comment]
@jillesvangurp any news on this?

**Comment by jillesvangurp** [comment]
Sorry, I've been really busy. I may have some time to spend on this next
week. I'll probably try to do a minimal fix for just the streaming first.

**Comment by pdpinheiro** [comment]
In the interim, the issue at hand is caused by a breaking change in Jersey Client v2.26. The fix is to add  a dependency on their DI package — `compile 'org.glassfish.jersey.inject:jersey-hk2:2.27'`. This currently causes a bunch of exceptions to be logged by jersey internals (I'll report back on a fix if I can find one), but seems to otherwise work fine.

**Comment by jillesvangurp** [comment]
Cool, would be great if you can give this a try. I also have a hunch that
shading is not helping here. In any case getting rid of jersey, is a good
thing. Really messy in it's requirements. I have one project where we have
it serverside and updating dependencies is becoming quite painful because
of it.

**Comment by pdpinheiro** [comment]
I'm currently vendoring the lib into my application and disabling shading because of issues around guava (it's currently not configured in the shadowJar renames), so that's probably not interfering with this particular issue.

**Comment by pdpinheiro** [comment]
Right, after digging around some more, the DI exceptions can be done away with by bringing in some Java EE bits:

```

**Comment by jillesvangurp** [comment]
@bartekn please check the updated PR for this.

**Comment by jillesvangurp** [comment]
BTW. I've released my fork on jitpack:

https://jitpack.io/#Inbot/java-stellar-sdk/v0.3.2.1-inbot-shaded-10
