### ISSUE TITLE
TransactionResponse fail to serialize to json, because private seed is null

### ISSUE THREAD

**Issue by cyberluke** [stellar/java-stellar-sdk#153]
Problem is here: https://github.com/stellar/java-stellar-sdk/blob/master/src/main/java/org/stellar/sdk/responses/TransactionResponse.java

Problem is:
```
  @SerializedName("source_account")
  private final KeyPair sourceAccount;

```
When it want to serialize KeyPair, it scream with exception about secretSeed cannot be serialized and converted into JSON.

This problem is in all responses with **source_account** property. Therefore currently I have to duplicate all these classes by hand, remove **source_account** property.

And every response it needs to iterate over all objects and transform them by hand just because of this:
```
for (TransactionResponse transactionResponse : transactionResponsePage.getRecords()) {
                GetTransaction transaction = new GetTransaction();
                transaction.setCreated(transactionResponse.getCreatedAt());
                transaction.setFee(transactionResponse.getFeePaid());
                transaction.setTxHash(transactionResponse.getHash());
                transactions.add(transaction);
}
```

Why GSON? Why don't you use Jackson.

**Comment by overcat** [comment]
I think this issue was fixed a long time ago, so I have decided to close it. If there are any more problems, please don't hesitate to reopen it.
