### ISSUE TITLE
Payment listeners not working properly

### ISSUE THREAD

**Issue by ishwar007** [stellar/java-stellar-sdk#157]
I am trying to connect to private hosted horizon server. I am trying to get payment's stream using PaymentListener. 

```
PaymentsRequestBuilder paymentsRequestBuilder = stellarHorizonServer.payments();

			String pagingToken = loadLastPagingToken();
			if (pagingToken != null) {
				paymentsRequestBuilder.cursor(pagingToken);
			}
			eventSource = paymentsRequestBuilder.forAccount(account).stream(operationsEventListener);
```

But I am getting "byebye" in response. 
This causes shadow.com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: "byebye". While SSEStream.java contains handling for "hello" as well as "goodbye", there's no handling for "byebye". 
Referring to this line: https://github.com/stellar/java-stellar-sdk/blob/cd338be65459c3a298827bd99c1459022506e5d0/src/main/java/org/stellar/sdk/requests/SSEStream.java#L183

I am using following versions of horizon,stellar-core and java-stellar-sdk.

```
horizon: v0.15.1
stellar-core: v10.0.0
java-stellar-sdk:0.4.0
```

Please refer to the attached screenshots for the same.

![image](https://user-images.githubusercontent.com/28685562/49659382-322baa80-fa6a-11e8-9f79-71cf9eccf12e.png)
 
Am I missing anything here? 
Appreciating any suggestions or help in advance.

**Comment by bartekn** [comment]
Please upgrade to [0.4.1](https://github.com/stellar/java-stellar-sdk/releases/tag/0.4.1).
