### ISSUE TITLE
how to set transaction fee?

### ISSUE THREAD

**Issue by linhtoji** [stellar/java-stellar-sdk#171]
builder() function in class Transaction create new transaction with fee:
`operations.length * BASE_FEE`

` public Transaction build() {
      Operation[] operations = new Operation[mOperations.size()];
      operations = mOperations.toArray(operations);
      Transaction transaction = new Transaction(mSourceAccount.getKeypair(), operations.length * BASE_FEE, mSourceAccount.getIncrementedSequenceNumber(), operations, mMemo, mTimeBounds);
      // Increment sequence number when there were no exceptions when creating a transaction
      mSourceAccount.incrementSequenceNumber();
      return transaction;
    }`

so we cannot change transaction fee?

**Comment by dabitdev** [comment]
why do you want to change the fee? 
The fee is defined by the network and by the number of operations.

**Comment by linhtoji** [comment]
@dabitdev Because the transaction is too slow, I want to pay extra for priority
