### ISSUE TITLE
base fee should be pulled from horizon

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/java-stellar-sdk#181]
comment that spun off this issue to be a separate issue: https://github.com/stellar/java-stellar-sdk/pull/177/files#r258731630

see the related js sdk issue: https://github.com/stellar/js-stellar-sdk/pull/234
see the related java sdk issue to add custom fee: https://github.com/stellar/java-stellar-sdk/issues/176

**Comment by overcat** [comment]
Now that we already have [surge pricing mode](https://developers.stellar.org/docs/encyclopedia/fees-surge-pricing-fee-strategies#surge-pricing), it seems to me that automatically setting the base fee from horizon doesn't make much sense, so I decided to close this issue. If there are any more problems, please don't hesitate to reopen it.
