### ISSUE TITLE
Exception thrown from ManageOfferOperation.fromXDR for certain offers

### ISSUE THREAD

**Issue by silent-grass** [stellar/java-stellar-sdk#183]
Hi, Stellar Team

**Version: 0.6.0**
I see the related issue, but nothing was fixed: stellar/java-stellar-sdk: Pull Request 97

Steps to reproduce:
Just invoke: ```org.stellar.sdk.Transaction.fromEnvelopeXdr(AAAAAButy5zasS3DLZ5uFpZHL25aiHUfKRwdv1+3Wp12Ce7XAAAAZAEyGwYAAAAOAAAAAAAAAAAAAAABAAAAAQAAAAAbrcuc2rEtwy2ebhaWRy9uWoh1HykcHb9ft1qddgnu1wAAAAMAAAAAAAAAAUtJTgAAAAAARkrT28ebM6YQyhVZi1ttlwq/dk6ijTpyTNuHIMgUp+EAAAAAAAARPSfDKZ0AAv7oAAAAAAAAAAAAAAAAAAAAAXYJ7tcAAABAbE8rEoFt0Hcv41iwVCl74C1Hyr+Lj8ZyaYn7zTJhezClbc+pTW1KgYFIZOJiGVth2xFnBT1pMXuQkVdTlB3FCw==)```

Result:
```**ArithmeticException: "Non-terminating decimal expansion; no exact representable decimal result" **```

Here
 ```
case MANAGE_OFFER:
        operation = new ManageOfferOperation.Builder(body.getManageOfferOp()).build();
        break;
```

Thanks.

**Comment by silent-grass** [comment]
@nullstyle It can happen for MANAGE_OFFER and CREATE_PASSIVE_OFFER operations.
Point is here: ManageOfferOperation.Builder/CreatePassiveOfferOperation.Builder:
**price = new BigDecimal(n).divide(new BigDecimal(d)).toString()**

Thanks.

**Comment by nullstyle** [comment]
@silent-grass thanks for the heads up.  I should have a fix in place soon, I just need to rework some things and put a regression test in place
