### ISSUE TITLE
TimeBounds has to be set or you must call setTimeout(TIMEOUT_INFINITE)

### ISSUE THREAD

**Issue by prettyCoders** [stellar/java-stellar-sdk#184]
It throw a exception when i start building the transaction use java sdk!

**Comment by rolivieri** [comment]
I just ran into this same issue as I was following the instructions here (java sdk): https://www.stellar.org/developers/guides/get-started/transactions.html

Then found this issue (js sdk): https://github.com/stellar/docs/issues/431. The same fix is needed for the sample Java code that is provided in the instructions. Invoking the `setTimeout()`  on the transaction builder object fixes this error.
