### ISSUE TITLE
Java SDK v0.7.0 Requirements Discussion

### ISSUE THREAD

**Issue by nullstyle** [stellar/java-stellar-sdk#189]
This issue will be a discussion place where we can gather requirements for a forthcoming release of the Java SDK for Stellar.  Please comment to include any of your desired inclusions/fixes/removals from this SDK.  The results of this discussion will feed into a roadmap that hopefully leads us to a more pleasant integration experience for developers from the JVM ecosystem.

Here's some initial requirements i've gathered from the issue list:

- Better error handling for streaming connections
- Better consistency of naming and usage
- Update dependencies to newer versions
- #185 
- Better support for android:  #156

**Comment by jillesvangurp** [comment]
@nullstyle thanks for getting started on this.

Here's my thoughts:

- Merge #182 #190 
- Get #187 over the finishing line; it fixes an important problem.
- #156, now that we have the jersey dependency out of the way, shadowing is no longer needed. I'm fine with removing that and maybe getting rid of a few more dependencies. I think guava is mostly redundant in this project and a bit of an obstacle for Android as there are two versions of it for jdk8+ and android.
- Make a decision on remaining pull requests. Most look like they are outdated or would need more work.
- go through older issues and verify if they are still relevant.

I'd be happy to help with some of this, time permitting. FYI, I maintain a Kotlin (https://github.com/Inbot/inbot-stellar-kotlin-wrapper) client that depends on this; and have an interest in keeping things moving forward.

**Comment by nullstyle** [comment]
@jillesvangurp Thanks for including your feedback, and thanks for doing code reviews in our PRs and including your inputs on the issues in this repo.  It is much appreciated.  That's awesome to see you've got a kotlin wrapper going... I've been meaning to play around with kotlin more and this seems like a good excuse :)

**Comment by jillesvangurp** [comment]
Go for it; I'd love to get some feedback on that.

**Comment by jillesvangurp** [comment]
Btw. I added this to the build file with a previous pull request:
https://github.com/stellar/java-stellar-sdk/blob/master/build.gradle#L15

so running `gradle dependencyUpdates -Drevision=release` will produce a list of outdated dependencies. Mostly the stuff is reasonably up to date but there probably have been a few minor releases of stuff since then.

**Comment by nullstyle** [comment]
Awesome, I had not seen that.  Thanks!

**Comment by nullstyle** [comment]
Alright, we've got a good list of things to do for v0.7.0 and I'm going to try to get them all wrapped up for a release at the halfway point of may.  Check out the milestone for the list of issues.
