### ISSUE TITLE
Extracting memo contents could be improved with helper

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/java-stellar-sdk#195]
As discussed in the SE question: https://stellar.stackexchange.com/questions/2442/retrieve-transaction-memo-text-with-java-api

> 

Memo is an abstract type that represents 5 different kinds of objects. The Java SDK does not define toString methods for these classes, so the printed output defaults to the toString method on Object. This is unhelpful, as you outlined.

> In order to print the memo text you first need to identify if the memo is of the right subtype, and then you need to cast it. It's a bit ugly. e.g.
> 
> if (txn.getMemo() instanceof MemoText) {
>   System.out.println(((MemoText) txn.getMemo()).getText());
> } else {
>   System.out.println(txn.getMemo());
> }
> 
We could a convenience method to basically do this for the user.

**Comment by overcat** [comment]
The `toString` method has been added.
