### ISSUE TITLE
Streaming request missing for offers

### ISSUE THREAD

**Issue by stepan-romankov** [stellar/java-stellar-sdk#208]
It's not possible to make a streaming request for offers however horizon API supports it.
See https://www.stellar.org/developers/horizon/reference/endpoints/offers-for-account.html

**Comment by overcat** [comment]
It seems to be missing, but it should be easy to add it.

**Comment by stepan-romankov** [comment]
Hi! Any plans to release this?

**Comment by overcat** [comment]
Implemented in #209
