### ISSUE TITLE
Support the Stellar memo convention.

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/java-stellar-sdk#21]
https://github.com/stellar/stellar-protocol/issues/28

Steps that need to happen when you handle an incoming message:
1. you receive a tx
2. Do you already have a preimage of the memo?
3. no -> Fetch the preimage
   - Look up the home domain of the source account
     - Fetch the stellar.toml
   - or, Look for a "msg_server" key on the account 
   - ask the MESSAGE_SERVER for the preimage of the tx memo
4. Check signature on any signed blocks.
5. Are there blocks that are encrypted?
   - Do we have the key?
   - yes -> decrypt
   - no -> ignore

after processing, the sdk should for each operation provide:
- note
- user info
- routing info 

---

We need to think a bit how we are going to implement this in the various sdk's @nullstyle

**Comment by overcat** [comment]
It seems that this discussion is outdated, so I have decided to close it.
