### ISSUE TITLE
Upgrade to Java 8

### ISSUE THREAD

**Issue by tamirms** [stellar/java-stellar-sdk#214]
Java 8 was released in 2014 and introduces a lot of nice features such as lambdas, streams,
and completable futures. By upgrading the Java Stellar SDK to use Java 8 we will be
able to take advantage of these features to improve the code quality of the Stellar client.

**Comment by stepan-romankov** [comment]
@tamirms have you seen the quality of Stellar Java SDK. Java 8 will not help. It's just buggy and incomplete. Moreover the Horizon API is poor and suites only for pet projects. You understand if try to work with Offers.

**Comment by jillesvangurp** [comment]
This will break compatibility with Android. It does not support Java 8.

**Comment by ardevd** [comment]
@jillesvangurp yes it does.

**Comment by ire-and-curses** [comment]
@ardevd thanks! Can you post a source for that statement?

**Comment by ardevd** [comment]
https://developer.android.com/studio/write/java8-support

**Comment by ire-and-curses** [comment]
Thanks! Looks like the support is partial, but this is still helpful.

**Comment by sreuland** [comment]
@tamirms ,  i think this ticket can be closed, the [sdk has been upgraded to 8 ](https://github.com/stellar/java-stellar-sdk/blob/master/build.gradle#L27)
