### ISSUE TITLE
Upgrade to JUnit 5

### ISSUE THREAD

**Issue by tamirms** [stellar/java-stellar-sdk#215]
Among other improvements, JUnit 5 provides cleaner ways to test cases when you expect an exception to be thrown. We want to avoid having both junit 4 and 5 on the classpath so we should attempt to upgrade all the tests to JUnit 5 in a single release

**Comment by theaeolianmachine** [comment]
Heads up @tamirms that this didn't get autoclosed probably because the PR was into the release-0.8.0 branch as opposed to master in case you'd like to go ahead and close this out.
