### ISSUE TITLE
Use CircleCI instead of TravisCI

### ISSUE THREAD

**Issue by tamirms** [stellar/java-stellar-sdk#219]

**Comment by Synesso** [comment]
Hi there. What's the benefit of switching?

**Comment by theaeolianmachine** [comment]
Hey @Synesso, so far we've seen it be _much_ faster. For the go monorepo, we went from an 11 minute build to a 2 minute build, and in general the platform team has been in favor of it since switching over.

**Comment by Synesso** [comment]
Good to know. Thanks @theaeolianmachine !
