### ISSUE TITLE
Support for SEP 10 challenge transaction

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/java-stellar-sdk#235]
SEP 10 describes a [specific form](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0010.md#response) for the "challenge" transaction used for authentication. Providing a helper at the SDK level makes sense to save users from reimplementing the spec.

Here are example implementations in [Go](https://github.com/stellar/go/pull/1468) and [JS](https://github.com/stellar/js-stellar-sdk/pull/375).

**Comment by dabitdev** [comment]
Is there any equivalent to the `WebAuthenticator` form the ios SDK?

**Comment by dabitdev** [comment]
my fault > Sep10Challenge.class

**Comment by leighmcculloch** [comment]
Closed by #264.
