### ISSUE TITLE
add support for querying operation endpoint with 'join' parameter

### ISSUE THREAD

**Issue by tamirms** [stellar/java-stellar-sdk#236]
Horizon v0.19 introduces a join parameter when querying for operations. This allows users to get transaction details with operation responses.

**Comment by ire-and-curses** [comment]
Go implementation: [go:1521](https://github.com/stellar/go/issues/1521)

**Comment by tamirms** [comment]
fixed in https://github.com/stellar/java-stellar-sdk/pull/242
