### ISSUE TITLE
Type org.stellar.sdk.responses.AssetResponse not present

### ISSUE THREAD

**Issue by bas24** [stellar/java-stellar-sdk#239]
Thank you for your efforts on this package.

Having strange exception from submitTransaction stating that AssetResponse not presented while building transaction for multiple assets and this happens only in --release build. I believe the only one response must be SubmitTransactionResponse for result of the transaction. But result of the transaction verifying with stellar.expert is correct - new trustlines established correctly.
Help please out on this

java-stellar-sdk version 0.8.1

Best Regards

**Comment by ire-and-curses** [comment]
This is hard to understand. Would you please provide a minimal example code demonstrating the problem, and paste the response you receive?

**Comment by bas24** [comment]
Sorry, was harrying and rewrote most to another way. Will close this issue. Thank you!
