### ISSUE TITLE
Support strict-send path finding API

### ISSUE THREAD

**Issue by wu-ziching** [stellar/java-stellar-sdk#247]
Doesn't look like this is supported right now. 

From the Horizon v0.21.0 release notes:

> /paths/strict-send can now accept a destination_account parameter. If destination_account is provided then the endpoint will return all payment paths which terminate with an asset held by destination_account. Note that the endpoint will accept destination_account or destination_assets but not both. destination_assets is a comma separated list of assets encoded as native or code:issuer.
/paths/strict-receive can now accept a source_assets parameter instead of source_account parameter. If source_assets is provided the endpoint will return all payment paths originating from an asset in source_assets. Note that the endpoint will accept source_account or source_assets but not both. source_assets is a comma separated list of assets encoded as native or code:issuer.

**Comment by tamirms** [comment]
fixed in 0.11.0 release
