### ISSUE TITLE
MemoId value can overflow

### ISSUE THREAD

**Issue by fracek** [stellar/java-stellar-sdk#249]
I believe the Java SDK is affected by the same bug as elucidsoft/dotnet-stellar-sdk#208. When the transaction `MemoId` value is larger than what can be stored in a `long`, it overflows resulting in a negative memo id. @Synesso confirmed the MemoId does indeed overflow.

This is the XDR of the transaction that led me to find the bug:

`AAAAAEdL24Ttos6RnqXCsn8duaV035/QZSC9RXw29IknigHpAAAD6AFb56cAAukDAAAAAQAAAAAAAAAAAAAAAF20fKAAAAACjCiEBz2CpG0AAAABAAAAAAAAAAEAAAAADq+QhtWseqhtnwRIFyZRdLMOVtIqzkujfzUQ22rwZuEAAAAAAAAAAGZeJLcAAAAAAAAAASeKAekAAABAE+X7cGoBhuJ5SDB8WH2B1ZA2RrWIXxGtx+n6wE5d/EggDTpZhRm92b33QqjPUFOfcZ+zbcM+Ny0WR2vcYHEXDA==`

And [here](https://www.stellar.org/laboratory/#xdr-viewer?input=AAAAAEdL24Ttos6RnqXCsn8duaV035%2FQZSC9RXw29IknigHpAAAD6AFb56cAAukDAAAAAQAAAAAAAAAAAAAAAF20fKAAAAACjCiEBz2CpG0AAAABAAAAAAAAAAEAAAAADq%2BQhtWseqhtnwRIFyZRdLMOVtIqzkujfzUQ22rwZuEAAAAAAAAAAGZeJLcAAAAAAAAAASeKAekAAABAE%2BX7cGoBhuJ5SDB8WH2B1ZA2RrWIXxGtx%2Bn6wE5d%2FEggDTpZhRm92b33QqjPUFOfcZ%2BzbcM%2BNy0WR2vcYHEXDA%3D%3D&type=TransactionEnvelope&network=public) a link to the laboratory, where the transaction is deserialized correctly.

**Comment by bartekn** [comment]
The reason why it's happening is because Java doesn't support unsigned logs and `uint64` is actually a type of `MemoId` in stellar-core.  There are special functions in Java 8 you can use to convert string from/to uint64 values: `Long.toUnsignedString` and `Long.parseUnsignedLong`. You can use them to encode/decode memo values higher than max int64.

**Comment by Synesso** [comment]
Ah right. The reason Scala works is because it provides a BigInteger method
and uses that in the toString.

BigInt(java.lang.Long.toUnsignedString(id))
