### ISSUE TITLE
[bug]maybe it is operations

### ISSUE THREAD

**Issue by fbaiesec** [stellar/java-stellar-sdk#253]
i find a bug(i think it is),in /sdk/requests/OperationsRequestBuilder,function 
`public OperationResponse operation(long operationId) throws IOException {
        this.setSegments(new String[]{"operation", String.valueOf(operationId)});
        return this.operation(this.buildUri());
    }`
the `new String[]{"operation"` maybe is `new String[]{"operations"`?

**Comment by tamirms** [comment]
fixed in 0.11.0 release
