### ISSUE TITLE
can not get transaction from transaction response

### ISSUE THREAD

**Issue by wumingmo** [stellar/java-stellar-sdk#284]
### What version are you using?
0.6.0

### What did you do?
public Transaction getTransaction(TransactionResponse transactionResponse) 
{
   byte[] bytes = Base64.getDecoder().decode(transactionResponse.getEnvelopeXdr());
   TransactionEnvelope transactionEnvelope = TransactionEnvelope.decode(new XdrDataInputStream(new ByteArrayInputStream(bytes)));
   return transactionEnvelope.getTx();
}

The above piece of code (using version 0.6.0) is used to get a transaction from a TransactionResponse. It has been working fine at least before May 1st. But now it always gave the error "java.lang.RuntimeException: Unknown enum value: 2" at TransactionEnvelope.decode. I have tested the return result from transactionResponse.getEnvelopeXdr() on stellar lab, and it can get the transaction there. I am wondering whether this is due to some latest version update.

Thanks

**Comment by abuiles** [comment]
@wumingmo you need to upgrade to the latest version of this library. This problem occurs because you are trying to read a transaction envelope from protocol 13.
