### ISSUE TITLE
How we can validate the stellar address(public key)?

### ISSUE THREAD

**Issue by emtalent9** [stellar/java-stellar-sdk#288]
### What problem does your feature solve?
Users can validate the other user's public key before calling any operation.

**Comment by overcat** [comment]
Can you provide a more detailed description?  Do you want to verify whether the address is correct, or whether the address exists in the network?

**Comment by overcat** [comment]
Due to the long period of inactivity on this issue, I have decided to close it. If there are any further problems, let us reopen it.
