### ISSUE TITLE
Revoke sponsorship exception

### ISSUE THREAD

**Issue by przemyslawcelinski** [stellar/java-stellar-sdk#304]
### What version are you using?
Version `0.21.0`

### What did you do?
I try to get accountId from operation revoke_sponsorship from testnet
transaction: `https://horizon-testnet.stellar.org/transactions/02a69bb0dc83d004ae918aab2d10c9dbc2cbf4451ab12927a691b87e5c6c5079/operations`

### What did you expect to see?
accountId from operation revoke_sponsorship from testnet

### What did you see instead?
```
NullPointerException:
java.lang.NullPointerException: null
	at shadow.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:888) ~[java-stellar-sdk-0.21.0.jar:0.19.0]
	at shadow.com.google.common.base.Optional.of(Optional.java:103) ~[java-stellar-sdk-0.21.0.jar:0.19.0]
	at org.stellar.sdk.responses.operations.RevokeSponsorshipOperationResponse.getAccountId(RevokeSponsorshipOperationResponse.java:53) ~[java-stellar-sdk-0.21.0.jar:0.19.0]
```

### Description: 
In `org.stellar.sdk.responses.operations.RevokeSponsorshipOperationResponse` is getter:
```
  public Optional<String> getAccountId() {
    return Optional.of(accountId);
  }
```
But accountId in transaction `02a69bb0dc83d004ae918aab2d10c9dbc2cbf4451ab12927a691b87e5c6c5079` is null.

All getters in this class have `Optional.of`

**Comment by ire-and-curses** [comment]
@przemyslawcelinski thanks! bug fix release here: https://github.com/stellar/java-stellar-sdk/releases/tag/0.21.1

**Comment by tamirms** [comment]
@przemyslawcelinski note that `02a69bb0dc83d004ae918aab2d10c9dbc2cbf4451ab12927a691b87e5c6c5079` is the source account for the operation. but, the operation is revoking sponsorship for an offer, not an account. So, the `getAccountId()` accessor will return an empty Optional value. The `sourceAccount()` accessor will return `02a69bb0dc83d004ae918aab2d10c9dbc2cbf4451ab12927a691b87e5c6c5079` and the `getOfferId()` accessor will return `Optional.of("8822470")`.
