### ISSUE TITLE
PathPaymentStrictReceiveOperation is missing "send_amount" 

### ISSUE THREAD

**Issue by tomerweller** [stellar/java-stellar-sdk#312]

**Comment by bartekn** [comment]
`PathPaymentStrictReceiveOperation` is used to build transactions and you don't define `send_amount` when creating a transaction. You should check [`PathPaymentStrictReceiveOperationResponse`](https://stellar.github.io/java-stellar-sdk/org/stellar/sdk/responses/operations/PathPaymentStrictReceiveOperationResponse.html).[`getSourceAmount()`](https://stellar.github.io/java-stellar-sdk/org/stellar/sdk/responses/operations/PathPaymentBaseOperationResponse.html#getSourceAmount--) after tx is submitted to the network.
