### ISSUE TITLE
Some RevokeSponsorship operations are missing Discriminant property

### ISSUE THREAD

**Issue by IgorNatanzon** [stellar/java-stellar-sdk#316]
### What did you do?
Creating following 4 operations:
RevokeAccountSponsorshipOperation
RevokeDataSponsorshipOperation
RevokeTrustlineSponsorshipOperation
RevokeClaimableBalanceSponsorshipOperation

When creating an XDR from resulting transaction, we get an error:
Cannot invoke "org.stellar.sdk.xdr.LedgerEntryType.getValue()" because the return value of "org.stellar.sdk.xdr.LedgerKey.getDiscriminant()" is null

This is because discriminant is not being set in the following:
RevokeClaimableBalanceSponsorshipOperation.java --> missing key.setDiscriminant(LedgerEntryType.CLAIMABLE_BALANCE) in toOperationBody() method
RevokeDataSponsorshipOperation.java --> missing key.setDiscriminant(LedgerEntryType.DATA)  
RevokeTrustlineSponsorshipOperation.java --> missing key.setDiscriminant(LedgerEntryType.TRUSTLINE)
RevokeAccountSponsorshipOperation.java --> missing key.setDiscriminant(LedgerEntryType.ACCOUNT)

I'm not familiar with the codebase yet to assume this is correct fix though, but it does seem to work when I make the above changes in a local jar

**Comment by overcat** [comment]
Would you mind sharing the code that can reproduce the problem? Thanks.

**Comment by IgorNatanzon** [comment]
`@Test

    public void testRevokeAccount()  {

        TransactionBuilderAccount txAccount = new Account("GC4JD5IZGBLTWUTF23NTDBXNMPRQGTWAVE5VUETYFUG44UIOICRYSUXS",12345L);

        Memo memo = Memo.none();

        Transaction.Builder builder = new Transaction.Builder(txAccount,Network.TESTNET)

                .addMemo(memo)

                .setBaseFee(100)

                .setTimeout(Transaction.Builder.TIMEOUT_INFINITE);

        RevokeAccountSponsorshipOperation revokeAccountSponsor = new RevokeAccountSponsorshipOperation.Builder("GC4JD5IZGBLTWUTF23NTDBXNMPRQGTWAVE5VUETYFUG44UIOICRYSUXS").build();

        builder.addOperation(revokeAccountSponsor);

        Transaction tx = builder.build();

        String xdr = tx.toEnvelopeXdrBase64();

    }

 

    @Test

    public void testRevokeTrustline()  {

        TransactionBuilderAccount txAccount = new Account("GC4JD5IZGBLTWUTF23NTDBXNMPRQGTWAVE5VUETYFUG44UIOICRYSUXS",12345L);

        Memo memo = Memo.none();

        Transaction.Builder builder = new Transaction.Builder(txAccount,Network.TESTNET)

                .addMemo(memo)

                .setBaseFee(100)

                .setTimeout(Transaction.Builder.TIMEOUT_INFINITE);

        Asset asset = new AssetTypeCreditAlphaNum12("TEST1","GC4JD5IZGBLTWUTF23NTDBXNMPRQGTWAVE5VUETYFUG44UIOICRYSUXS");

        RevokeTrustlineSponsorshipOperation revokeTrustlineSponsorshipOperation = new RevokeTrustlineSponsorshipOperation.Builder("GC4JD5IZGBLTWUTF23NTDBXNMPRQGTWAVE5VUETYFUG44UIOICRYSUXS",asset).build();

        builder.addOperation(revokeTrustlineSponsorshipOperation);

        Transaction tx = builder.build();

        String xdr = tx.toEnvelopeXdrBase64();

    }`

I apologise for formatting, had to do it on my phone 

Both of these examples generate a get Discriminant() is null error unless the fix above is made. Same happens with the other two revoke operations.

**Comment by overcat** [comment]
@IgorNatanzon Thank you for your feedback. It seems that `discriminant` is not set in the code, I will submit a PR later.

**Comment by overcat** [comment]
@IgorNatanzon fixed in 0.22.1

**Comment by IgorNatanzon** [comment]
@overcat Awesome, thank you!
