### ISSUE TITLE
Feature Request: Provide a simple way for decoding the public key as simple String.

### ISSUE THREAD

**Issue by VicMikhailau** [stellar/java-stellar-sdk#318]
Hi, Stellar SDK team

### What problem does your feature solve?
Provide a simple way for decoding the public key as simple String

### What would you like to see?
`StrKey.class` is closed. Maybe makes sense to make it opened?

### What alternatives are there?
I don't see any other solutions. E.g. I have '_Set Option Operation_' with the _Signer_ object. I have used `KeyPair.fromXdrSignerKey(operation.signer).accountId` for retrieve String representation of Public Key. But in some cases, it returns '_Invalid Public Key_' exception -> '_not a valid GroupElement_'. Good. But I just need to try to decode the byte array in this case.
Can you please suggest any other solution to retrieve a simple String representation of Public Key e.g. from the byte array? 

On IOS SDK it retrieved like `PublicKey(xdr: x).accountId`

On Backend just used:
```
key = StrKey.decode_ed25519_public_key(public_key)
return Keypair.from_raw_ed25519_public_key(key)
```
**Summary:**  It would be nice if the SDK had simple methods available for decoding, for example, an array of bytes (e.g for _ed25519.uint256_). As in the _StrKey.class_, which is closed. 

Thanks.

**Comment by tamirms** [comment]
@VicMikhailau `StrKey.encodeStellarAccountId()` will convert an `AccountID` instance into a string. If that function does not help you can you please provide a specific example with a sample public key

**Comment by VicMikhailau** [comment]
> @VicMikhailau `StrKey.encodeStellarAccountId()` will convert an `AccountID` instance into a string. If that function does not help you can you please provide a specific example with a sample public key

It's worked fine (I need just to receive simple String public key representation and have bytes array of operation.signer.ed25519.uint256):
StrKey.encodeStellarAccountId(byte[] data).

Just check the inner method of the KeyPair class. It use StrKey.encodeStellarAccountId(byte[] data).
```
KeyPair -> public String getAccountId() {
        return StrKey.encodeStellarAccountId(this.mPublicKey.getAbyte());
    }
```

E.g. on Backend just used:
key = StrKey.decode_ed25519_public_key(public_key)
return Keypair.from_raw_ed25519_public_key(key)

**Comment by VicMikhailau** [comment]
@tamirms Updated issue description.
Summary:  It would be nice if the SDK had simple methods available for decoding, for example, an array of bytes (e.g for _ed25519.uint256_). As in the _StrKey.class_, which is closed. For cases when the Public Key can be not valid for some reason and must be just decoded as String.

Thanks.

**Comment by overcat** [comment]
Should we provide some utils for converting addresses, values, and other information in XDR?
[A few of functions](https://github.com/StellarCN/py-stellar-base/blob/master/stellar_sdk/xdr/utils.py) are currently available in the Python SDK, I may add more in the future depending on user demand.

**Comment by VicMikhailau** [comment]
@overcat Why not? Sounds good. Additional methods and etc can be always useful. 
Thanks.

**Comment by let-it-snow** [comment]
Please do the StrKey.class public. It can help avoiding the StrKey.class duplication on the app side.

Use case:

```
org.stellar.sdk.xdr.SC Address Type.SC_ADDRESS_TYPE_ACCOUNT ->
StrKey.encodeStellarAccountId(address.accountId.accountID.ed25519.uint256)
```
