### ISSUE TITLE
Tests shouldn't make requests to real servers.

### ISSUE THREAD

**Issue by paulbellamy** [stellar/java-stellar-sdk#342]
### What version are you using?

OpenJDK 8

### What did you do?

Ran the tests.

### What did you expect to see?

No http requests to the outside world while running tests.

### What did you see instead?

That there are network requests to `horizon.stellar.org` and others.

### More Info

See: https://github.com/stellar/java-stellar-sdk/pull/339/commits/04a113a960aebd41d713510b3f0b10e0fb2a056e

**Comment by bartekn** [comment]
Are you sure there were network requests in the commit you added here? That's true that the mocked responses contains real horizon URLs but I think it's just a mocked string.

**Comment by paulbellamy** [comment]
Well.. Before the linked commit the test was failing with a 503. Once I replaced the urls in the next page link, it started succeeding with the expected 200. So it's talking to *somewhere* unexpected. Not sure whether that's a real network or not.

**Comment by bartekn** [comment]
Oh, it's about `nextPage`. I understand now 👍 .
