### ISSUE TITLE
why  "stream"  doesn't return data?

### ISSUE THREAD

**Issue by peppapigz** [stellar/java-stellar-sdk#352]
### What version are you using?

name: 'java-stellar-sdk', version: '0.24.0'

### What did you do?
 ```
1.
public static SSEStream<OfferResponse> queryOffer() {
        RequestBuilder reb = getTestServer().offers().order(RequestBuilder.Order.ASC);
        return ((OffersRequestBuilder) reb).forSeller("GABVZPSEHHPF5KVUVAR5YVAI3QMWVKTKREJKQ5WJNUBIVQQTEIT72R2M").stream(new BacEventListener4());
} 

2.
public static SSEStream<OfferResponse> queryOffer2() {
        RequestBuilder reb = getTestServer().offers().order(RequestBuilder.Order.ASC);
        return ((OffersRequestBuilder) reb).forAccount("GABVZPSEHHPF5KVUVAR5YVAI3QMWVKTKREJKQ5WJNUBIVQQTEIT72R2M").stream(new BacEventListener4());
}

3.
public static Page<OfferResponse> queryOffer3() throws Exception {
        RequestBuilder reb = getTestServer().offers().order(RequestBuilder.Order.DESC).limit(200);
        return ((OffersRequestBuilder) reb).forSeller("GABVZPSEHHPF5KVUVAR5YVAI3QMWVKTKREJKQ5WJNUBIVQQTEIT72R2M").execute();
}

```

### What did you expect to see?
Method 1  return data.

### What did you see instead?

Method 1 and Method 2 are stream mode, and Method 3 is http query.

Among them, the method called by Method 1 is forSeller(), and the stream does not return any data. The method called by Method 2 is forAccount(), and stream pushes offers data normally. The method called by Method 3 is forSeller(), and the data is returned normally. 

**Please tell me why Method 1 doesn't return data?**

**Comment by overcat** [comment]
1. /offers is not streamable
https://github.com/stellar/go/blob/4670509a3e872359fbe11f6ee0383ecf883e8ace/services/horizon/internal/httpx/router.go#L178

2. /accounts/{account_id}/offers is streamable
https://github.com/stellar/go/blob/4670509a3e872359fbe11f6ee0383ecf883e8ace/services/horizon/internal/httpx/router.go#L202-L203
