### ISSUE TITLE
Feature Request: Add grace period to SEP-10 challenge parsing function

### ISSUE THREAD

**Issue by JakeUrban** [stellar/java-stellar-sdk#358]
### What problem does your feature solve?

Its possible for the SEP-10 challenge's `minTime` constraint to be "in the future" for the client application parsing the challenge due to clock drift.

### What would you like to see?

We've implemented a grace period for the min time constraint in the [Go SDK](https://github.com/stellar/go/pull/3824), and both the min and max time in the [JS SDK](https://github.com/stellar/js-stellar-sdk/pull/667). I'd like us to do the same here.

### What alternatives are there?

N/A

**Comment by salimwyre** [comment]
👍 When using the SDK as a client and the test anchor as a server we hit that case "minTime in the future" about 5% of the time
![Timing issue](https://user-images.githubusercontent.com/90262484/133663656-586d672a-910c-419f-b3ed-b592e7e3e45a.png)
