### ISSUE TITLE
Cannot use a network : Constructor not visible.

### ISSUE THREAD

**Issue by chainhead** [stellar/java-stellar-sdk#37]
The following does not compile.

```
private String PRIVATE_NETWORK = System.getenv("NETWORK_PASSPHRASE");
Network.use(new Network(PRIVATE_NETWORK));
```
The error message is:

```
The constructor Network(String) is not visible.
```

What is the way to use to a custom network?

**Comment by bartekn** [comment]
Which version are you using? This should be possible in the latest ([0.1.9](https://github.com/stellar/java-stellar-sdk/releases/tag/0.1.9)) version. Please let me know if it doesn't work for you.

**Comment by chainhead** [comment]
Yes; got it working with 0.1.9. Thanks!
