### ISSUE TITLE
Analysis of LIQUIDITY_POOL_SHARES type assets in AccountResponse.balance cannot obtain LiquidityPoolID

### ISSUE THREAD

**Issue by shenhao217** [stellar/java-stellar-sdk#375]
Hello,The reason is that AccountResponse is being parsed. Balance corresponds to SerializedName without liquidity_pool_id

**Comment by sreuland** [comment]
> Hello,The reason is that AccountResponse is being parsed. Balance corresponds to SerializedName without liquidity_pool_id

Hello @shenhao217 , can you provide client code excerpt showing the sdk invocation which lacks LiquidityPoolID, i.e. is it AccountReponse.Balance.getLiquidityPoolID() or pertaining to the Asset returned from AccountReponse.Balance.getAsset() ?

**Comment by shenhao217** [comment]
Hello, thank you for your attention. This is when I call the client code AccountReponse.Balance.getLiquidityPoolID().get(), but the returned LiquidityPoolID object is empty, resulting in an IllegalStateException being thrown. The AccountReponse.Balance object except for LiquidityPool I can't get other attributes, which makes me have to add the attribute of SerializedName as liquidity_pool_id to the object.
