### ISSUE TITLE
When the query effect data type returns 95, there will be a gson parsing exception

### ISSUE THREAD

**Issue by shenhao217** [stellar/java-stellar-sdk#393]
Hello, I found a bug in version 0.29.0. When the data type returns LiquidityPoolRevokedEffectResponse, the return parameter reserves_revoked should be accepted as an array instead of entity classes.

**Comment by TimC71** [comment]
Same here. Try it with version 0.29.0

>     public static void main(String[] args) throws IOException {
>        Page<EffectResponse> page = server.effects().forLedger(38837940).cursor("166807682144149505-6")
>                .order(RequestBuilder.Order.ASC).limit(1).execute();
>        System.out.println("done");
>    }

will throw a 
> java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $.reserves_revoked

exception.

**Comment by gologo13** [comment]
This issue is still happening with version 0.40. SDK.
When will it be resolved?

**Comment by overcat** [comment]
Sorry for the inconvenience caused. The issue have been fixed in [0.40.1](https://github.com/stellar/java-stellar-sdk/releases/tag/0.40.1).
