### ISSUE TITLE
Call getAsset from TrustlineCreatedEffectResponse class

### ISSUE THREAD

**Issue by przemyslawcelinski** [stellar/java-stellar-sdk#396]
What version are you using?
Version 0.30.0

What did you do?
Call method

```
  public Asset getAsset() {
    if (assetType.equals("native")) {
      return new AssetTypeNative();
    } else {
      return Asset.createNonNativeAsset(assetCode, assetIssuer);
    }
  }
```
from `TrustlineCreatedEffectResponse` class

Operation "change_trust" in block 38115883 with effect `trustline_created`
https://horizon.stellar.org/transactions/a0a65ac4d71e44fc2be2bb071645a16a577efe6258e610214ab5dc60309c9798/effects which has
"asset_type": "liquidity_pool_shares" but assetCode and assetIssuer are null. So in Asset.createNonNativeAsset(assetCode, assetIssuer); is thrown NullPointerException

```
  public static Asset createNonNativeAsset(String code, String issuer) {
    if (code.length() >= 1 && code.length() <= 4) {
      return new AssetTypeCreditAlphaNum4(code, issuer);
    } else if (code.length() >= 5 && code.length() <= 12) {
      return new AssetTypeCreditAlphaNum12(code, issuer);
    } else {
      throw new AssetCodeLengthInvalidException();
    }
  }
```

I added comment to closed issue: https://github.com/stellar/java-stellar-sdk/issues/374#issuecomment-1004622229

**Comment by sreuland** [comment]
@przemyslawcelinski , thanks for report, yes, it looks like similar issue of mapping liquidity pools as asset from json into an sdk class, in this case TrustLineCUDResponse didn't map liquidity pool id and pass it to asset creation, I'm going through the effects and operations classes overall to get them all consistent.
