### ISSUE TITLE
It's not clear how to set the sequence number on an Account appropriately when creating a new account.

### ISSUE THREAD

**Issue by myrle-krantz** [stellar/java-stellar-sdk#4]
Perhaps it is better not to offer a method of construction which accepts the sequence number at all, since the sequence number can better be programmatically acquired as part of an sdk.Account object.

**Comment by bartekn** [comment]
We need to allow to pass sequence number somehow in the API. Imagine [cold wallet](https://en.bitcoin.it/wiki/Cold_storage) application: sequence number will be typed by a user in a text field. Please reopen if you don't agree.

**Comment by myrle-krantz** [comment]
I learned something.  Thank you.
