### ISSUE TITLE
SDK has been waiting for the problem when calling the account method

### ISSUE THREAD

**Issue by mayong82** [stellar/java-stellar-sdk#400]
// First, check to make sure that the destination account exists.
// You could skip this, but if the account does not exist, you will be charged
// the transaction fee when the transaction fails.
// It will throw HttpResponseException if account does not exist or there was another error.
server.accounts().account(destination.getAccountId());

When the receiving account does not exist, the SDK program will always be stuck here, and the program cannot continue

**Comment by overcat** [comment]
We are unable to reproduce this issue. and due to the long period of inactivity on this issue, I have decided to close it. If there are any more problems, please don't hesitate to reopen it.
