### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by EV6999** [stellar/java-stellar-sdk#403]
### What version are you using?
0.31.0

### What did you do?
There is no null check for liquidityPoolID. 
When liquidityPoolID is null, liquidityPoolID.toString() causes an error.

https://github.com/stellar/java-stellar-sdk/blob/24426ee0256b330aa4bc0d5d361bd161f[…]e9/src/main/java/org/stellar/sdk/responses/AccountResponse.java

**Comment by vinamogit** [comment]
Duplicate of #405
