### ISSUE TITLE
Protocol 19 SDK Support

### ISSUE THREAD

**Issue by Shaptic** [stellar/java-stellar-sdk#409]
There are four elements to updating SDKs to support Protocol 19:

- [x] stellar/go#4260
- [x] stellar/go#4262
- [x] stellar/go#4281
- [ ] Updating API definitions in SDKs to handle the updated schemas from (1) and (2).

The last item is blocked until the Horizon API is finalized (i.e. after the PRs are merged).

**Comment by sreuland** [comment]
I think #411 and #410 are stories that combined will duplicate the scope of this ticket, they breakout the effort for both main CAPs further.

**Comment by Shaptic** [comment]
Yep! Plus just updating the XDR itself which you can break out as you see fit, @sreuland.
