### ISSUE TITLE
Update StrKey implementation to support CAP-40 signed payloads

### ISSUE THREAD

**Issue by Shaptic** [stellar/java-stellar-sdk#410]
Java-specific issue for the parent, stellar/go#4262.

**Comment by Shaptic** [comment]
Closed by stellar/java-stellar-sdk#414.

**Comment by nkavian** [comment]
This PR made the signers list immutable. We need the ability to clear the signers and get the unsigned structure.

 - Could we get a `clearSignatures()` method added to the class?
 - Is there an alternate way to clear signatures?

**Comment by nkavian** [comment]
@sreuland  This PR made the signers list immutable. We need the ability to clear the signers and get the unsigned structure.

 - Could we get a `clearSignatures()` method added to the class?
 - Is there an alternate way to clear signatures?

**Comment by sreuland** [comment]
> @sreuland This PR made the signers list immutable. We need the ability to clear the signers and get the unsigned structure.
> 
> * Could we get a `clearSignatures()` method added to the class?
> * Is there an alternate way to clear signatures?

Hello @nkavian , I [responded on issue #456](https://github.com/stellar/java-stellar-sdk/issues/456#issuecomment-1257291282) with suggestions on some alternatives, thanks!
