### ISSUE TITLE
Offers for Account has a error

### ISSUE THREAD

**Issue by ywdlucking** [stellar/java-stellar-sdk#42]
class AssetDeserializer implements JsonDeserializer<Asset> {
  @Override
  public Asset deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
    String type = json.getAsJsonObject().get("asset_type").getAsString();
    **if (type == "native") {**
      return new AssetTypeNative();
    } else {
      String code = json.getAsJsonObject().get("asset_code").getAsString();
      String issuer = json.getAsJsonObject().get("asset_issuer").getAsString();
      return Asset.createNonNativeAsset(code, KeyPair.fromAccountId(issuer));
    }
  }
}

type == "native" is not equal

**Comment by bartekn** [comment]
You can't compare strings like this in Java. Use [`String.equals`](https://stackoverflow.com/a/767379) method.

**Comment by ywdlucking** [comment]
i kown , but the code is copied from java-stellar-sdk
