### ISSUE TITLE
SSEStream status monitoring

### ISSUE THREAD

**Issue by lijamie98** [stellar/java-stellar-sdk#432]
### What problem does your feature solve?

While implementing the health check of the Stellar Platform Server, we need to check if the stream's executor service is live and running properly. 

### What would you like to see?
Make the status of the [ExecutorService ](https://github.com/stellar/java-stellar-sdk/blob/master/src/main/java/org/stellar/sdk/requests/SSEStream.java#L36) available. 

Create getters for the following statuses:
```java
  private final AtomicBoolean isStopped = new AtomicBoolean(false);
  private final AtomicBoolean serverSideClosed = new AtomicBoolean(true); // make sure we start correctly
  private final AtomicReference<String> lastEventId = new AtomicReference<String>(null);
```
https://github.com/stellar/java-stellar-sdk/blob/master/src/main/java/org/stellar/sdk/requests/SSEStream.java#L33-L35

**Comment by overcat** [comment]
We have improved the retry mechanism in the latest code, but currently I have not exposed isStopped and serverSideClosed. Only when the close function is called, isStopped will be set to true. In other cases, it remains true. serverSideClosed may be set to true by the server, but the sse module will immediately reconnect, so it will also be immediately set back to false.
