### ISSUE TITLE
Add `memo` support in Sep10Challenge

### ISSUE THREAD

**Issue by lijamie98** [stellar/java-stellar-sdk#434]
### What problem does your feature solve?

Sep10Challenge.newChallenge() does not support `memo` field. This is blocking MGI from supporting custodial wallet.

### What would you like to see?

An overloaded `Sep10Challenge.newChallenge()` taking `memo` as an argument.

**Comment by overcat** [comment]
Implemented in c08777583c10b5405962a19866365477127f8f6c
