### ISSUE TITLE
Fix CircleCI action "Publish Release on GitHub"

### ISSUE THREAD

**Issue by marcelosalloum** [stellar/java-stellar-sdk#441]
### What version are you using?

`0.34.1`

### What did you do?

Create a new release to publish a new version of the SDK.

### What did you expect to see?

The CD/CI jobs should run smoothly and the GH release should have been updated with the `*.jar` file.

### What did you see instead?

The CircleCI [job failed](https://app.circleci.com/pipelines/github/stellar/java-stellar-sdk/512/workflows/dd4db4ac-2bac-4302-aa91-c51f22097642/jobs/629) and I had to upload the jar manually in the release.

**Comment by overcat** [comment]
Fixed in #512, this issue can be closed.
