### ISSUE TITLE
CI: Release tagging not publishing artifacts to GH release page

### ISSUE THREAD

**Issue by sreuland** [stellar/java-stellar-sdk#449]
### What version are you using?
latest

### What did you do?

Tagged a new release

### What did you expect to see?

The new tagged release build jar file added to the Github release

### What did you see instead?
no release jar artifact added to the Github release, the CI step to publish the release build jar to GH release is failing on `ghr` tool

**Comment by sreuland** [comment]
cc @tamirms

**Comment by marcelosalloum** [comment]
I installed ghr using homebrew and it worked fine. Seems like the go version (used in the pipeline) is having problems though.
