### ISSUE TITLE
Possible error on xdr string/array enconding, align to 4 bytes missing

### ISSUE THREAD

**Issue by bnogalm** [stellar/java-stellar-sdk#45]
According to 
https://docs.oracle.com/cd/E26502_01/html/E35597/xdrproto-31244.html#xdrproto-41

strings/arrays must be aligned to 4 bytes.

testManageDataOperation test fills an array with 5 bytes.

and it expects as a result:
AAAAAQAAAAC7JAuE3XvquOnbsgv2SRztjuk4RoBVefQ0rlrFMMQvfAAAAAoAAAAEdGVzdAAAAAEAAAAFAAECAwQ=

When it should be: AAAAAQAAAAC7JAuE3XvquOnbsgv2SRztjuk4RoBVefQ0rlrFMMQvfAAAAAoAAAAEdGVzdAAAAAEAAAAFAAECAwQAAAA=

**Comment by bnogalm** [comment]
Sorry all the edit/close/changes, i am very unsecure when i feel i find out that something is wrong.
I find out this writing my C++ SDK port from this. I don't know if other implementations are working in the same way. 
By the moment, i will match this SDK implementation.

**Comment by bartekn** [comment]
I confirm it's a bug. We need to update xdrgen first: https://github.com/stellar/xdrgen/pull/28 Then I will update Java SDK code and release a new version. Thanks for catching this.
