### ISSUE TITLE
Signers were made immutable causing a breaking change

### ISSUE THREAD

**Issue by nkavian** [stellar/java-stellar-sdk#456]
### What version are you using?

Java 0.29.0 upgrading to 0.37.2

### What did you do?

`transaction.getSignatures().clear();`

### What did you expect to see?

With older versions of the SDK, I could clear the signatures and perform my necessary logic.

 - Could we get a `AbstractTransaction.clearSignatures()` method added to the class?
 - Is there an alternate way to clear signatures?

### What did you see instead?

The signatures list is now immutable. Our engineer has to arcanely copy and modify code from the SDK in order to remove the signature; which is not the right solution.

This PR https://github.com/stellar/java-stellar-sdk/issues/410 made the signers list immutable.

**Comment by sreuland** [comment]
Yes, that was mentioned in the [0.32.0 release](https://github.com/stellar/java-stellar-sdk/blob/master/CHANGELOG.md?plain=1#L62-L64) as part of overall protocol 19 updates.  Has the tx instance you're working with already had `sign()` invoked, i.e. there are signatures in its collection? if not, it's empty, can use `addSignature()` as recommended for additive update to signatures collection. Other option is to rebuild the tx with TransactionBuilder, and then re-invoke the `sign()` methods to build out the signatures again.

**Comment by nkavian** [comment]
Hi @sreuland thanks for following up. My use case is this scenario:
 - we generate an encrypted hash of the original unsigned transaction.
 - we give the encrypted hash and the unsigned transaction to the client. We don't keep a copy of the hash in our DB.
 - the client signs the request, and hands us back the encrypted hash with the signed transaction.
 - At this point, we want to clear signatures and recompute the encrypted hash, and verify if it matches the original.
Instead of trusting one particular field `transactionHash` we verify the full contents of the structure since it came from the outside. We need confirmation we're not passing along some other generated or modified transaction.

**Comment by nkavian** [comment]
@secondclaw that was really helpful, we're able to avoid the longer chunk of code we had built.

I'm okay to use this workaround and I'm fine if this ticket is closed. Would still like to see if the SDK can add a `clearSignatures` method directly.
