### ISSUE TITLE
Add unit test coverage to verify android sdk version support

### ISSUE THREAD

**Issue by sreuland** [stellar/java-stellar-sdk#458]
### What problem does your feature solve?
verify min android sdk versions work with packaged/shadowed jar distributable.

### What would you like to see?
a unit test that can run the android emulator for a given android sdk version, such as 28, with a sample apk project like Basic Activity template from the android studio - https://github.com/stellar/java-stellar-sdk/issues/450#issuecomment-1248152732

**Comment by overcat** [comment]
Implemented in #514.
