### ISSUE TITLE
send Friendbot the public key to create and fund a new account not working behind proxy

### ISSUE THREAD

**Issue by davidathuil** [stellar/java-stellar-sdk#464]
### What version are you using?
plugins {
	id 'java'
	id 'org.springframework.boot' version '2.6.11'
	id 'io.spring.dependency-management' version '1.0.13.RELEASE'
}

version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

repositories {
	mavenCentral()
	maven { url 'https://jitpack.io' }

}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'com.github.stellar:java-stellar-sdk:0.38.0'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

### What did you do?
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.stellar.sdk.KeyPair;

        import java.net.*;
        import java.io.*;
        import java.util.*;
        import org.stellar.sdk.Server;
        import org.stellar.sdk.responses.AccountResponse;
        @SpringBootApplication
        public class BlocksyStellarApplication {

	public static void main(String[] args) throws IOException {
		SpringApplication.run(BlocksyStellarApplication.class, args);
	KeyPair pair = KeyPair.random();
        System.out.println(new String(pair.getSecretSeed()));
        System.out.println(pair.getAccountId());
        String friendbotUrl = String.format(
				"https://friendbot.stellar.org/?addr=%s",
				pair.getAccountId());
		InputStream response = null;
		try {
			response = new URL(friendbotUrl).openStream();
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
		String body = new Scanner(response, "UTF-8").useDelimiter("\\A").next();
		System.out.println("SUCCESS! You have a new account :)\n" + body);

		Server server = new Server("https://horizon-testnet.stellar.org");
		AccountResponse account = server.accounts().account(pair.getAccountId());
		System.out.println("Balances for account " + pair.getAccountId());
		for (AccountResponse.Balance balance : account.getBalances()) {
			System.out.printf(
					"Type: %s, Code: %s, Balance: %s%n",
					balance.getAssetType(),
					balance.getAssetCode(),
					balance.getBalance()
			);
		}
	}
}

### What did you expect to see?
**ok when i desactivate my proxy**

SCNQT2DUAHIYBXMVSESJGPTSZCQM6ZVVSU6CKPSPOKC7RK2BCFMEWHCA
GABGJUBHWPCKHJ5MSBJHPWUOC54NXB47CVTAHZUTUF5MKKZGG3SGITY4
SUCCESS! You have a new account :)
{
  "_links": {
    "self": {
      "href": "https://horizon-testnet.stellar.org/transactions/c21f172ddcfd768fe77b633d68fffe6cc49504f639c334619a2e289bd251ce32"
    },
    "account": {
      "href": "https://horizon-testnet.stellar.org/accounts/GAQ3LAQHX3FYDGXY6FPSOWAMFPIOWLN66EHPAOYMUXYXFUQZ2UREUCTP"
    },
    "ledger": {
      "href": "https://horizon-testnet.stellar.org/ledgers/698711"
    },
    "operations": {
      "href": "https://horizon-testnet.stellar.org/transactions/c21f172ddcfd768fe77b633d68fffe6cc49504f639c334619a2e289bd251ce32/operations{?cursor,limit,order}",
      "templated": true
    },
    "effects": {
      "href": "https://horizon-testnet.stellar.org/transactions/c21f172ddcfd768fe77b633d68fffe6cc49504f639c334619a2e289bd251ce32/effects{?cursor,limit,order}",
      "templated": true
    },
    "precedes": {
      "href": "https://horizon-testnet.stellar.org/transactions?order=asc\u0026cursor=3000940894359552"
    },
    "succeeds": {
      "href": "https://horizon-testnet.stellar.org/transactions?order=desc\u0026cursor=3000940894359552"
    },
    "transaction": {
      "href": "https://horizon-testnet.stellar.org/transactions/c21f172ddcfd768fe77b633d68fffe6cc49504f639c334619a2e289bd251ce32"
    }
  },
  "id": "c21f172ddcfd768fe77b633d68fffe6cc49504f639c334619a2e289bd251ce32",
  "paging_token": "3000940894359552",
  "successful": true,
  "hash": "c21f172ddcfd768fe77b633d68fffe6cc49504f639c334619a2e289bd251ce32",
  "ledger": 698711,
  "created_at": "2023-01-25T21:10:00Z",
  "source_account": "GAQ3LAQHX3FYDGXY6FPSOWAMFPIOWLN66EHPAOYMUXYXFUQZ2UREUCTP",
  "source_account_sequence": "1249835483321",
  "fee_account": "GAQ3LAQHX3FYDGXY6FPSOWAMFPIOWLN66EHPAOYMUXYXFUQZ2UREUCTP",
  "fee_charged": "2000",
  "max_fee": "1000000",
  "operation_count": 1,
  "envelope_xdr": "AAAAAgAAAAAhtYIHvsuBmvjxXydYDCvQ6y2+8Q7wOwyl8XLSGdUiSgAPQkAAAAEjAAAAuQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAABB90WssODNIgi6BHveqzxTRmIpvAFRyVNM+Hm2GVuCcAAAAAAAAAAACZNAns8Sjp6yQUnfajhd424efFWYD5pOhesUrJjbkZAAAABdIdugAAAAAAAAAAAIZ1SJKAAAAQCcZDJrmePcmpb0im8JlAaap2sQ3/TUGJy7y5WXO0Y8Q7aY7GMSw6tq/T5Zxmw52wGQm0r+2/CExszN/9Ggm1Q2GVuCcAAAAQA4ZYhDR/c3Lk9ZC7NHntiVoAzOYI9NWamSACOprZp84YH4ye8jRy/jhPhGCBOXbfxTvgO8XU34+Khs6SYL44wE=",
  "result_xdr": "AAAAAAAAB9AAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAA=",
  "result_meta_xdr": "AAAAAgAAAAIAAAADAAqpVwAAAAAAAAAAIbWCB77LgZr48V8nWAwr0OstvvEO8DsMpfFy0hnVIkoAAAAAOqk4AgAAASMAAAC4AAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAAACqCfAAAAAGPRbNYAAAAAAAAAAQAKqVcAAAAAAAAAACG1gge+y4Ga+PFfJ1gMK9DrLb7xDvA7DKXxctIZ1SJKAAAAADqpOAIAAAEjAAAAuQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAAqpVwAAAABj0ZqoAAAAAAAAAAEAAAADAAAAAwAKqVYAAAAAAAAAABB90WssODNIgi6BHveqzxTRmIpvAFRyVNM+Hm2GVuCcAOLHrRUiL2QAAADhAAAAZAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAAABhgAAAABjmZxhAAAAAAAAAAEACqlXAAAAAAAAAAAQfdFrLDgzSIIugR73qs8U0ZiKbwBUclTTPh5thlbgnADix5XMq0dkAAAA4QAAAGQAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAAAAYYAAAAAY5mcYQAAAAAAAAAAAAqpVwAAAAAAAAAAAmTQJ7PEo6eskFJ32o4XeNuHnxVmA+aToXrFKyY25GQAAAAXSHboAAAKqVcAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAA",
  "fee_meta_xdr": "AAAAAgAAAAMACqCfAAAAAAAAAAAhtYIHvsuBmvjxXydYDCvQ6y2+8Q7wOwyl8XLSGdUiSgAAAAA6qT/SAAABIwAAALgAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAAKoJ8AAAAAY9Fs1gAAAAAAAAABAAqpVwAAAAAAAAAAIbWCB77LgZr48V8nWAwr0OstvvEO8DsMpfFy0hnVIkoAAAAAOqk4AgAAASMAAAC4AAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAAACqCfAAAAAGPRbNYAAAAA",
  "memo_type": "none",
  "signatures": [
    "JxkMmuZ49yalvSKbwmUBpqnaxDf9NQYnLvLlZc7RjxDtpjsYxLDq2r9PlnGbDnbAZCbSv7b8ITGzM3/0aCbVDQ==",
    "DhliENH9zcuT1kLs0ee2JWgDM5gj01ZqZIAI6mtmnzhgfjJ7yNHL+OE+EYIE5dt/FO+A7xdTfj4qGzpJgvjjAQ=="
  ],
  "valid_after": "1970-01-01T00:00:00Z",
  "preconditions": {
    "timebounds": {
      "min_time": "0"
    }
  }
}
Balances for account GABGJUBHWPCKHJ5MSBJHPWUOC54NXB47CVTAHZUTUF5MKKZGG3SGITY4
Type: native, Code: Optional.absent(), Balance: 10000.0000000

### What did you see instead?

Caused by: java.net.ConnectException: Connection timed out: connect

**Comment by overcat** [comment]
I think this issue is unrelated to the SDK. Here's an example to help you request friendbot through a proxy.

```java
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.InetSocketAddress;
import java.net.Proxy;
import java.net.URL;

public class StellarProxyDemo {
    public static void main(String[] args) throws Exception {
        String addr = "GDQLRSZHCAYLO2STS6H5LQJU2HGXCVLMEFPZVFOL7XSRH5GJ3SM2HL7X";
        String url = String.format("https://friendbot.stellar.org/?addr=%s", addr);

        String proxyHost = "127.0.0.1";
        int proxyPort = 7890;

        Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyHost, proxyPort));
        URL obj = new URL(url);
        HttpURLConnection con = (HttpURLConnection) obj.openConnection(proxy);
        con.setRequestProperty("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36");

        // Set the request method to GET
        con.setRequestMethod("GET");

        // Read the response from the input stream
        BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
        String inputLine;
        StringBuilder response = new StringBuilder();
        while ((inputLine = in.readLine()) != null) {
            response.append(inputLine);
        }
        in.close();

        // Print the response
        System.out.println(response);
    }
}
```
