### ISSUE TITLE
Migrate from CircleCI to Github Actions

### ISSUE THREAD

**Issue by mollykarcher** [stellar/java-stellar-sdk#467]
### What problem does your feature solve?

Moves this repo over to the company-standard, which is Github Actions. Not urgent, but this would be good to do at some point. This and Kelp seem to be the only 2 repos still left on CircleCI.

### What would you like to see?

CI/CD handled exclusively in github actions

### What alternatives are there?

Keep everything in Circle

**Comment by overcat** [comment]
Implemented this in #512, this issue can be closed.
