### ISSUE TITLE
Support for new InvokeHostFunctionOperation

### ISSUE THREAD

**Issue by sreuland** [stellar/java-stellar-sdk#472]
### What problem does your feature solve?
lack of support for InvokeHostFunctionOperation in api response marshaling.

### What would you like to see?
support for marshaling the InvokeHostFunctionOp operation in any api responses ([protocol definition](https://github.com/stellar/go/blob/soroban-xdr-next/protocols/horizon/operations/main.go#L348-L358)). 
a builder for constructing I
Includes using new strkey encoding for contract addresses, which may be present in the `to/from` fields of the `InvokeHostFunctionOp:AssetBalanceChanges`

related to SDK Epic - https://github.com/stellar/java-stellar-sdk/issues/490

### What alternatives are there?
n/a

**Comment by sreuland** [comment]
@tsachiherman , @mollykarcher , should the support level in the java SDK begin with inclusion of this recent update for multiple Function's as array in xdr model of InvokeHostFunctionOp, the Function model was singular prior:

https://github.com/stellar/stellar-xdr/commit/b721f812a353e15db286b6e1a3c095b9be9f4bd4

Is the multi-function model intended to be part of Preview 9?

**Comment by tsachiherman** [comment]
yes, the multi-function is going to be on preview 9, although we haven't scheduled any particular time to migrate our SDKs for that.

**Comment by tsachiherman** [comment]
If we could provide a minimal support for our SDK to support only a single function, that would likely to be acceptable - although I don't know if it would be possible. ( due to the way the SDK treat XDR ).

**Comment by sreuland** [comment]
ok, the java sdk has a layer of class abstractions for OperationResponse's in general that end clients use and these encapsulate the json emitted from Horizon Rest API, which does closely follow the xdr models, but not necessarily verbatim.

Current soroban enabled horizon emits the single function model of InvokeHostFunctionOp, and will start the java sdk support against that InvokeHostFunctionOp model. Since multi-function is intended to be part of preview9 xdr schema, we will need to update the soroban enabled horizon as part of that to parse/emit the multi-function model of InvokeHostFunctionOp, and then can change java sdk to parse the newer json of InvokeHostFunctionOp correctly afterwards.

thanks for clarification.

**Comment by tsachiherman** [comment]
> ok, the java sdk has a layer of class abstractions for OperationResponse's in general that end clients use and these encapsulate the json emitted from Horizon Rest API, which does closely follow the xdr models, but not necessarily verbatim.
> 
> Current soroban enabled horizon emits the single function model of InvokeHostFunctionOp, and will start the java sdk support against that InvokeHostFunctionOp model. Since multi-function is intended to be part of preview9 xdr schema, we will need to update the soroban enabled horizon as part of that to parse/emit the multi-function model of InvokeHostFunctionOp, and then can change java sdk to parse the newer json of InvokeHostFunctionOp correctly afterwards.
> 
> thanks for clarification.

All correct. On go, I've created 
https://github.com/stellar/go/pull/4854 to address that. I'm waiting for core to complete their release so I can test these changes.

**Comment by sreuland** [comment]
ok, thanks, am contributing to https://github.com/stellar/go/pull/4854, updating the 'Details' json output for InvokeHostFunctionOp to serialize multi-functions per Op now, which having that updated json model is a pre-req before start here.

**Comment by overcat** [comment]
Implemented in #481.
