### ISSUE TITLE
java-stellar-sdk: add support for fees

### ISSUE THREAD

**Issue by tsachiherman** [stellar/java-stellar-sdk#479]
### What ?

The fees changes as well as the multi-operation invoke host function change requires some changes to the sdk.

### Epic

https://github.com/stellar/java-stellar-sdk/issues/470

**Comment by sreuland** [comment]
This scope will likely focus on just fees, need to investigate where fees need to show up in sdk, and where they will come from in the horizon api. 

There is new multi-function InvokeHostFunctionOp model that has been introduced in xdr, and I think that aspect will be pulled into the sdk on #472 as part of initial support for InvokeHostFunctionOp on responses.

**Comment by sreuland** [comment]
@overcat implemented this on #492
