### ISSUE TITLE
Exception while decoding a transaction envelope containing a custom asset operation

### ISSUE THREAD

**Issue by efritze** [stellar/java-stellar-sdk#48]
```  
    //This works.
    @Test 
    public void decodeTransactionEnvelopeWithNativeAsset() throws IOException {

        String transactionEnvelopeToDecode = "AAAAACq1Ixcw1fchtF5aLTSw1zaYAYjb3WbBRd4jqYJKThB9AAAAZAA8tDoAAAAEAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAHMXLrCwa9tH+ABeAAPp1pgmHqBS9e0879ylTSHCrChUAAAAAAAAAAB3NZQAAAAAAAAAAAA==";
        Base64 base64Codec = new Base64();

        byte[] bytes = base64Codec.decode(transactionEnvelopeToDecode);

        TransactionEnvelope transactionEnvelope = TransactionEnvelope.decode(new XdrDataInputStream(new ByteArrayInputStream(bytes)));
        //no exceptions thrown here :)

        org.stellar.sdk.xdr.Transaction tx = transactionEnvelope.getTx();

        assertEquals(100, tx.getFee().getUint32().intValue());
        //this works.Yoopie!

    }

    //This doesn't work.
    @Test 
    public void decodeTransactionEnvelopeWithCustomAsset() throws IOException {

        String transactionEnvelopeToDecode = "AAAAACq1Ixcw1fchtF5aLTSw1zaYAYjb3WbBRd4jqYJKThB9AAAAZAA8tDoAAAALAAAAAAAAAAEAAAAZR29sZCBwYXltZW50IGZvciBzZXJ2aWNlcwAAAAAAAAEAAAAAAAAAAQAAAAARREGslec48mbJJygIwZoLvRtL6/gGL4ss2TOpnOUOhgAAAAFHT0xEAAAAACq1Ixcw1fchtF5aLTSw1zaYAYjb3WbBRd4jqYJKThB9AAAAADuaygAAAAAAAAAAAA==";

        Base64 base64Codec = new Base64();

        byte[] bytes = base64Codec.decode(transactionEnvelopeToDecode);

        TransactionEnvelope transactionEnvelope = TransactionEnvelope.decode(new XdrDataInputStream(new ByteArrayInputStream(bytes)));
        //TransactionEnvelope.decode is throwing the following exception :(
//        **Caused by: java.lang.RuntimeException: Unknown enum value: 21450572**
//	at org.stellar.sdk.xdr.AssetType.decode(AssetType.java:41) ~[stellar-1.jar:0.1.12]
//	at org.stellar.sdk.xdr.Asset.decode(Asset.java:72) ~[stellar-1.jar:0.1.12]
//	at org.stellar.sdk.xdr.PaymentOp.decode(PaymentOp.java:50) ~[stellar-1.jar:0.1.12]
//	at org.stellar.sdk.xdr.Operation$OperationBody.decode(Operation.java:207) ~[stellar-1.jar:0.1.12]
//	at org.stellar.sdk.xdr.Operation.decode(Operation.java:78) ~[stellar-1.jar:0.1.12]
//	at org.stellar.sdk.xdr.Transaction.decode(Transaction.java:121) ~[stellar-1.jar:0.1.12]
//	at org.stellar.sdk.xdr.TransactionEnvelope.decode(TransactionEnvelope.java:47) ~[stellar-1.jar:0.1.12]

        //unreachable code below.
        org.stellar.sdk.xdr.Transaction tx = transactionEnvelope.getTx();

        assertEquals(100, tx.getFee().getUint32().intValue());

    }
```

**Comment by efritze** [comment]
I've done some further investigations.
The issue wasn't with the custom asset.
The issue was with the memo text. (_Payment for ABCD services_)

**Specifically, any transaction created on the Javascript side gets rejected on the Java side if it has a memo of more than 16 characters.**

The transaction envelope was created in Javascript, and I tried to decode it in Javascript.
It appears on the Javascript side the maximum number of characters is 24 characters (bytes), meanwhile the maximum number of characters the Java side can parse is 16 characters.

It might be an encoding issue, or the way Java represents strings.

**Comment by efritze** [comment]
Another example that breaks in Java:

https://www.stellar.org/laboratory/#txbuilder?params=eyJhdHRyaWJ1dGVzIjp7InNvdXJjZUFjY291bnQiOiJHQVZMS0lZWEdESzdPSU5VTFpOQzJORlEyNDNKUUFNSTNQT1dOUUtGM1lSMlRBU0tKWUlIMlJVUSIsInNlcXVlbmNlIjoiMTcwODY2NTk4MDM3NDIyMTkiLCJmZWUiOiIxMDAiLCJtZW1vVHlwZSI6Ik1FTU9fVEVYVCIsIm1lbW9Db250ZW50IjoiYWJjZGVmZ2hpamtsbW5vcXIifSwib3BlcmF0aW9ucyI6W3siaWQiOjE1MDYwNzU4MzcxNTksIm5hbWUiOiJwYXltZW50IiwiYXR0cmlidXRlcyI6eyJkZXN0aW5hdGlvbiI6IkdBVkxLSVlYR0RLN09JTlVMWk5DMk5GUTI0M0pRQU1JM1BPV05RS0YzWVIyVEFTS0pZSUgyUlVRIiwiYXNzZXQiOnsidHlwZSI6Im5hdGl2ZSIsImNvZGUiOiJHT0xEIiwiaXNzdWVyIjoiR0FWTEtJWVhHREs3T0lOVUxaTkMyTkZRMjQzSlFBTUkzUE9XTlFLRjNZUjJUQVNLSllJSDJSVVEifSwiYW1vdW50IjoiMTAwIn19XX0%3D&network=test

The above breaks while decoding in Java because the memo text (abcdefghijklmnopqr) has 17 characters.

If I change the memo text to (abcdefghijklmnopq) with 16 characters, I'm able to successfully decode the transaction envelope in Java.

**Comment by bartekn** [comment]
Fix is ready for a review: https://github.com/stellar/java-stellar-sdk/pull/49 Thanks!

**Comment by efritze** [comment]
I tested the fix. 
It works.
Thanks.
