### ISSUE TITLE
Add support for Soroban RPC server.

### ISSUE THREAD

**Issue by overcat** [stellar/java-stellar-sdk#485]
### What problem does your feature solve?
Enable users to invoke Soroban RPC services through this SDK

### What would you like to see?
We need to add the following functions:
- getAccount
- getHealth
- getNetwork
- getContractData
- getLedgerEntries
- getTransaction
- getEvents
- getLatestLedger
- simulateTransaction
- prepareTransaction
- sendTransaction

### What alternatives are there?
None

Estimated working hours: 24

**Comment by sreuland** [comment]
can refer to the javascript sdk, [server.ts](https://github.com/stellar/js-soroban-client/blob/main/src/server.ts), for reference example of sdk method signatures for wrapping the soroban rpc endpoints.

**Comment by overcat** [comment]
Implemented in #492.
