### ISSUE TITLE
Add support for BumpFootprintExpirationOperation and RestoreFootprintOperation Responses.

### ISSUE THREAD

**Issue by overcat** [stellar/java-stellar-sdk#486]
### What problem does your feature solve?

BumpFootprintExpirationOperation and RestoreFootprintOperation are newly introduced operations in the Protocol Soroban, and we need to add corresponding support for them.

### What would you like to see?
- Allow users to construct transactions that include these two operations.
- The server needs to be able to parse these two operations correctly. ([protocol](https://github.com/stellar/go/blob/soroban-xdr-next/protocols/horizon/operations/main.go#L369-L381))

### What alternatives are there?
None

Estimated working hours: 6

**Comment by sreuland** [comment]
I updated the title to narrow the scope to just supporting response models. The TransactionBuilder and TxSub aspects of these ops will need a new ticket created like 'Support TxSub for Invoke/Bump/Restore', and that will require soroban rpc integration and new flows for assembling transactions with preflight response data for setting tx footprint, fees. the js sdk, js-soroban-client, has gone through this enhancement for submitting tx's with these ops and preflighting, which can be used as a reference - https://github.com/stellar/js-soroban-client/pull/108

**Comment by overcat** [comment]
Implemented in #491.
