### ISSUE TITLE
Add some APIs to make it more convenient for users to construct InvokeHostFunction.

### ISSUE THREAD

**Issue by overcat** [stellar/java-stellar-sdk#488]
### What problem does your feature solve?

Currently, users need to construct InvokeHostFunction directly. I want to add some interfaces to help users quickly construct operations such as calling contracts and creating contracts.

### What would you like to see?

Add the following interfaces.
- upload_contract_wasm
- create_contract
- deploy_create_token_contract_from_asset
- deploy_create_token_contract_from_address
- invoke_contract_function

### What alternatives are there?
None

Estimated working hours: 8

**Comment by sreuland** [comment]
this is great coverage, it might be worthwhile to split the functions up into sub-tickets if you prefer. for 'invoke_contract_function`, could use the js sdk's [Contract.call() ](https://github.com/stellar/js-stellar-base/blob/soroban/src/contract.js) as a reference.

**Comment by overcat** [comment]
Implemented in #497.
