### ISSUE TITLE
Add support for Auth Next.

### ISSUE THREAD

**Issue by overcat** [stellar/java-stellar-sdk#489]
### What problem does your feature solve?
We need to add an interface for users to add signatures in the `InvokeHostFunctionOperation.auth`.

### What would you like to see?

I have added [an implementation](https://github.com/StellarCN/py-stellar-base/blob/48b55f32fa2eb8a5418afae48a51f3234936287e/stellar_sdk/soroban/authorization_entry.py) in the Python SDK, but I'm not sure if it is the optimal solution. I would like to have more discussion on this.

Related discussion: https://github.com/stellar/js-stellar-base/pull/632
### What alternatives are there?
None

Estimated working hours: TBD, more discussion is needed.

**Comment by overcat** [comment]
Hi @sreuland, I want to release a beta version after completing https://github.com/stellar/java-stellar-sdk/issues/490, so that users can have an early experience and provide feedback.

But due to the lack of sufficient discussion on Auth Next at present, I would like to exclude it from this release and postpone it to a later release. Do you think this is acceptable? We can wait for it to be completed in the JS/Python SDK first.

**Comment by sreuland** [comment]
yes, sounds like a good approach. Let's pull #489 out of #490. 

What will this mean for the type of soroban transactions which can be built and submitted by the first beta java sdk release? Sounds like would mean tx source account is the only address used in contract auths, i.e. [SOROBAN_CREDENTIALS_SOURCE_ACCOUNT](https://soroban.stellar.org/docs/fundamentals-and-concepts/invoking-contracts-with-transactions#authorization-data) and that auth entry is built by default with simulation response? 

thanks!

**Comment by overcat** [comment]
> yes, sounds like a good approach. Let's pull #489 out of #490.
> 
> What will this mean for the type of soroban transactions which can be built and submitted by the first beta java sdk release? Sounds like would mean tx source account is the only address used in contract auths, i.e. [SOROBAN_CREDENTIALS_SOURCE_ACCOUNT](https://soroban.stellar.org/docs/fundamentals-and-concepts/invoking-contracts-with-transactions#authorization-data) and that auth entry is built by default with simulation response?
> 
> thanks!

Yes, this means that users can only use the `SOROBAN_CREDENTIALS_SOURCE_ACCOUNT` authentication method, but this is sufficient to meet the majority of current needs. Let's take a break and then come back to improve other content.

**Comment by overcat** [comment]
Implemented in #537.
