### ISSUE TITLE
Uint32 should not be represented using Integer.

### ISSUE THREAD

**Issue by overcat** [stellar/java-stellar-sdk#494]
### What version are you using?
c258f0d5cf4b734e2bed4ccfbcf3c27dcee0dcb4

### What did you do?
https://github.com/stellar/java-stellar-sdk/blob/c258f0d5cf4b734e2bed4ccfbcf3c27dcee0dcb4/src/main/java/org/stellar/sdk/xdr/Uint32.java#L15

Uint32 represents an unsigned 32-bit integer, which has a range of 0 to 2^32-1.
Integer in Java represents a signed 32-bit integer, which has a range of -2^31 to 2^31-1.

### What did you expect to see?
We should use Long instead of Integer.

### What did you see instead?
N/A

**Comment by sreuland** [comment]
@overcat , do you think this issue may need to be raised in [xdrgen](https://github.com/stellar/xdrgen) ? as this code comes from that correct?
