### ISSUE TITLE
Update XDR reference

### ISSUE THREAD

**Issue by sreuland** [stellar/java-stellar-sdk#515]
### What problem does your feature solve?
there is a newer version of xdr available for Protocol 20, soroban:
stellar-xdr:7015193879e9da7cb70d889a49eecf494fefe7e1

for reference, same update to xdr being done on mono repo here:
https://github.com/stellar/go/pull/5023/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52

### What would you like to see?
the xdr generated classes in java are updated to this version of xdr and any compile time issues that may arise are resolved.

**Comment by sreuland** [comment]
@overcat , might be good to hold on doing this xdr version until we know it's confirmed, there's another adjustment about to land - https://github.com/stellar/stellar-xdr/pull/137

**Comment by sreuland** [comment]
@overcat , I think it's getting closer to stable for xdr version for next release, this latest xdr version may be the candidate to generate from, the js sdk is sitting on this version for now also:

https://github.com/stellar/stellar-xdr/tree/65afa63b7f52c898143ebbe9541ef91fcf290ade

**Comment by overcat** [comment]
Implemented in #530.
