### ISSUE TITLE
AllowTrustOperation asset code is not trimmed after being parsed from XDR

### ISSUE THREAD

**Issue by Synesso** [stellar/java-stellar-sdk#62]
Perhaps this is intentional, but it doesn't seem correct.

A roundtrip from AllowTrustOperation to XDR and back will keep unprintable characters at the tail of the asset code, if the code does not exactly meet 4 or 12 characters.

New failing test case:

```
  @Test
  public void testAllowTrustOperationAssetCodeBuffer() throws IOException, FormatException {
    // GC5SIC4E3V56VOHJ3OZAX5SJDTWY52JYI2AFK6PUGSXFVRJQYQXXZBZF
    KeyPair source = KeyPair.fromSecretSeed("SC4CGETADVYTCR5HEAVZRB3DZQY5Y4J7RFNJTRA6ESMHIPEZUSTE2QDK");
    // GDW6AUTBXTOC7FIKUO5BOO3OGLK4SF7ZPOBLMQHMZDI45J2Z6VXRB5NR
    KeyPair trustor = KeyPair.fromSecretSeed("SDHZGHURAYXKU2KMVHPOXI6JG2Q4BSQUQCEOY72O3QQTCLR2T455PMII");

    String assetCode = "USDABC";
    boolean authorize = true;

    AllowTrustOperation operation = new AllowTrustOperation.Builder(trustor, assetCode, authorize)
        .setSourceAccount(source)
        .build();

    org.stellar.sdk.xdr.Operation xdr = operation.toXdr();
    AllowTrustOperation parsedOperation = (AllowTrustOperation) Operation.fromXdr(xdr);

    assertEquals(assetCode, parsedOperation.getAssetCode());
  }
```

```
org.junit.ComparisonFailure: 
Expected :USDABC
Actual   :USDABC□□□□□□
```

**Comment by bnogalm** [comment]
I comment what i know
Asset codes get serialized to a fixed char array padded with zeroes
That is why when you read it back, you get the asset name with zeros at the end.
Maybe the string should be resized (trimmed) to the first \0 
I can say my C++ port behave the same way.

**Comment by bartekn** [comment]
I confirm it's a bug. `AllowTrustOperation.getAssetCode` shouldn't return padding null bytes. Because it's not a major issue I'm adding "help wanted" label.

**Comment by Synesso** [comment]
Contribution form signed. PR submitted.
Thanks
