### ISSUE TITLE
Provide the sdk in the popular maven repos

### ISSUE THREAD

**Issue by janprill** [stellar/java-stellar-sdk#64]
Developers who develop for the jvm (be it in java, scala, kotlin or the like) usually like to add their dependencies in the usual build tools. Therefore it would make sense to put the sdk on jcenter and maven central.

**Comment by berlinguyinca** [comment]
yes please provide us with this to make life a little bit easier!

**Comment by asebak** [comment]
Agreed.

**Comment by berlinguyinca** [comment]
for the time being, we added it to our public repository at 

http://gose.fiehnlab.ucdavis.edu:55000/content/groups/public

feel free to use it

**Comment by berlinguyinca** [comment]
http://gose.fiehnlab.ucdavis.edu:55000/content/groups/public updated to latest version.

**Comment by superstructor** [comment]
This is really inconvenient and #72 was merged 2 weeks ago. Can you please make this a priority @bartekn ?

**Comment by bedlaj** [comment]
I am using service jitpack.io, it works really well. 

**Add jitpack repository:**
>
    <repositories>
        <repository>
          <id>jitpack.io</id>
          <url>https://jitpack.io</url>
        </repository>
    </repositories>

**For latest release use dependency version 0.20:**
>
    <dependency>
        <groupId>com.github.stellar</groupId>
          <artifactId>java-stellar-sdk</artifactId>
          <version>0.2.0</version>
    </dependency>

More info: https://jitpack.io/#stellar/java-stellar-sdk

**Comment by superstructor** [comment]
Thanks for the jitpack.io suggestion @bedlaj, I'll try that with [`clj-stellar-sdk`](https://github.com/xlm-sg/clj-stellar-sdk).

It is surprising that this is still unresolved 3 months later.

**Comment by superstructor** [comment]
Have confirmed that jitpack.io instructions in README.md work with `clj-stellar-sdk`](https://github.com/xlm-sg/clj-stellar-sdk).

Thanks.

**Comment by bartekn** [comment]
Have you added `repositories` section?

```gradle
repositories {
    maven { url "https://jitpack.io" }
}
```
