### ISSUE TITLE
Precision of `Price`

### ISSUE THREAD

**Issue by Synesso** [stellar/java-stellar-sdk#65]
A `Price` instance can be created from a String representation of a BigDecimal, with the caveat that it is an _approximate_ value.

Are there any invariants on the input String in regard to number of significant digits? I've found that it can give some nasty results, but I don't know if the values I'm providing are outside expected usage.

e.g. `"14327483647.52312312"` approximates to `1 / 0`.

A user may create a `ManageOfferOperation` with a value such as this and would get quite an unexpected result. It would be good to understand the input invariants and assert them.

Additionally, it would be good to understand how much variance can be expected on the approximated result.

**Comment by bartekn** [comment]
Javadoc for `Price.fromString` states that it:
> Approximates `price` to a fraction.

However you are correct that there should be a way to create a `Price` object directly so we should probably make it's constructor public.

**Comment by Synesso** [comment]
Thanks @bartekn. I'm looking at this from the perspective of trying to grok the sdk and the capabilities of the Stellar network, rather than an actual user. 

I'm keen to understand how real users use this. 

Is an offer in the form of 

- `100 AUD for 80 USD`

or
- `100 AUD for USD at a rate of 0.8`

or both?

By adding a direct construction, are you saying this class accommodates both approaches?

**Comment by bartekn** [comment]
Price in Stellar network is represented as a fraction (numerator/denominator). From the [docs](https://www.stellar.org/developers/guides/concepts/list-of-operations.html#manage-offer):
> [price is a] Price of 1 unit of selling in terms of buying. For example, if you wanted to sell 30 XLM and buy 5 BTC, the price would be {5,30}.

So basically "100 AUD for 80 USD" and "100 AUD for USD at a rate of 0.8" means the same thing represented in a different way. In terms of low-level stellar-code code the former representation is more accurate. `Price.fromString` is just a helper method that translates a string value to n/d representation.

**Comment by Synesso** [comment]
Excellent. Thanks again.
