### ISSUE TITLE
Unknown enum value when decoding TransactionResult

### ISSUE THREAD

**Issue by MrSystem** [stellar/java-stellar-sdk#67]
I submitted a transaction to Stellar Core v9.0.1 through the HTTP interface and I got the following response:
```{"status":"ERROR","error":"AAAAAAAAJxD////7AAAAAA=="}```
According to the documentation for Stellar Core tx command, the error field is of type `TransactionResult`.
So I'm trying to decode it this way:
```
import org.stellar.sdk.xdr.TransactionResult;

TransactionResult result = TransactionResult.decode(new XdrDataInputStream(new ByteArrayInputStream("AAAAAAAAJxD////7AAAAAA==".getBytes())));
```
However I'm getting the following exception:
```
java.lang.RuntimeException: Unknown enum value: 1249395759
	at org.stellar.sdk.xdr.TransactionResultCode.decode(TransactionResultCode.java:71)
	at org.stellar.sdk.xdr.TransactionResult$TransactionResultResult.decode(TransactionResult.java:104)
	at org.stellar.sdk.xdr.TransactionResult.decode(TransactionResult.java:66)
```
Am I doing something wrong? Have there been any protocol changes that are causing this?

**Comment by bartekn** [comment]
You can use XDR Viewer in Laboratory to decode it: https://www.stellar.org/laboratory/#xdr-viewer?input=AAAAAAAAJxD%2F%2F%2F%2F7AAAAAA%3D%3D&type=TransactionResult&network=test

When it comes to your decoding code TransactionResult is base64 encoded so you need to decode it first and then use it in `XdrDataInputStream`.
