### ISSUE TITLE
Fee charged for transfer is part of the response?

### ISSUE THREAD

**Issue by myrle-krantz** [stellar/java-stellar-sdk#7]
This could be useful as part of the API.  Especially since I will need to keep Mifos and Stellar state synchronized.

**Comment by nullstyle** [comment]
@myrle-krantz could I ask you some question regarding this need?  I've been given some context by @bartekn but I want to make sure I'm understanding the situation.

From what I understand the specific API you are talking about is the "Transaction submission" API.  I'm assuming at some point near where you are submitting the transaction you are crafting it using the `org.stellar.base.Transaction`.  If that's the case, getting the fee that was paid is just the following code (assuming `tx` is an instance of `org.stellar.base.Transaction`):

```java
tx.toXdr().getFee();
```

Is there a reason in your use case that this is not available to you?  I'm definitely not opposed to adding ` fee_paid` field to the server response from horizon, I just want to make sure we're actually covering your needs.  You specifically mention this is needed for keeping states between Mifos and the stellar network synchronized:  To me that implies that much more required information than just the fee information.   If that is the case, could you explain a little bit about what other information you'll be keeping in sync on the Mifos side?

Presently, the recommended way to get all the information associated with a transaction submission is to load the "transaction" link from the submission response (it's at the json path `_links.transaction.href` if you have an example response handy).  The response will return all of the transaction level information (fee paid, memo data, signature data, etc.), and additionally contains links to the operation information associated with the transaction as well.

While this model of linked data will at present require you to do one or a couple of extra HTTP requests to load all of the data you might need, this inefficiency will be improved in the future with a system similar to how facebook's graph api allows you the "expand" fields in their responses.

**Comment by myrle-krantz** [comment]
Hi Scott.  Thank  you for the quick response.  That does indeed cover my use case. I hadn't found that solution because the xdr.Transaction is not documented in the base documentation that I'm using, and because it hadn't occurred to me to hunt there in the code.  Is the fee defined in the transaction instead of by the server?  That's surprising.

So: at very least you should find a way to document this.

The question of whether I would need more state is one I can't yet answer.  If I come across something else I need, I'll let you know.

**Comment by nullstyle** [comment]
The fee the user has elected to pay is set in the transaction and a minimum fee is enforced by the server.    If a transaction has declared fee under the minimum fee defined by the server it will fail.  

Fee information is documented here:  https://www.stellar.org/developers/learn/concepts/fees.html

**Comment by bartekn** [comment]
I added `Transaction.getFee()` in https://github.com/stellar/java-stellar-base/commit/1477fcf60c97df077f4f67a56b49fcc0981bfa87. We created `java-stellar-base` so developers don't have to interact with XDR classes (at least in the most common scenarios).

**Comment by myrle-krantz** [comment]
Thank you.
