### ISSUE TITLE
SEP-0005 (and BIP-39)

### ISSUE THREAD

**Issue by PegasusWallet** [stellar/java-stellar-sdk#74]
99% of the code is already done in BitcoinJ and really just a matter of rewriting the Key derivation to use the right "ed25519 seed" instead of "Bitcoin seed"

@bartekn Do you already have something planned or should I go ahead and prepare a PR ?

**Comment by bartekn** [comment]
Not sure how BitcoinJ works internally but if there are no add-ons it is most likely using secp256k1 curve whereas Stellar is using ed25519. So it's not only about changing the seed.

Anyway, if you decide to do it I think we should have another package for key derivation that allows developers to generate a secret seed for a given mnemonic seed and key path that can later be used to create a `Keypair` object.

**Comment by PegasusWallet** [comment]
Yes indeed there is actually way more work that what I thought. secp256k1  is heavily hardcoded in bitcoinj code using buncycasttle (which does not even support ed25519  but only curve25519) and all the interesting classes are final which makes it difficult to reuse the code. 

I had a try already by using ed25519 but I was not getting the right results.. I will spend a bit more time on this and try correlate with the GO version (which I just noticed was done by you)

**Comment by elucidsoft** [comment]
Hey guys, I wrote a .NET version of BIP39 based on the Javascript one.  It's fully functional, we plan to integrate this into our .NET SDK.  But could you use this as a starting point for the Java version maybe?  It has zero external dependencies which were one of the goals, so it does not depend on any external frameworks.

**Comment by bartekn** [comment]
@elucidsoft I glanced at your repository and it seems there's the same problem I mentioned in my first comment. Specifically:
> Not sure how BitcoinJ works internally but if there are no add-ons it is most likely using secp256k1 curve whereas Stellar is using ed25519. 

Also, what do you mean by saying:
> But could you use this as a starting point for the Java version maybe?

**Comment by elucidsoft** [comment]
That's a non issue with ed25519. Mainly what I meant was to remove the dependency issue you have with BitcoinJ.

**Comment by elucidsoft** [comment]
Yeah, I am nearly done with the BIP44 one as well. I am using the same HMAC ed25519 implementation from Chaos that I did for the wallet. This should be the last piece I need to do this...

**Comment by elucidsoft** [comment]
Ok so I finally got some time to work on this, I have published the results here https://github.com/elucidsoft/dotnetstandard-bip32/tree/master

It's working and all the unit tests mentioned in the spec are passing.

**Comment by elucidsoft** [comment]
So I went ahead and built a tiny little HD Wallet Project as well with a bunch of unit tests that combines BIP39 and BIP32 together to demonstrate it working.  https://github.com/elucidsoft/dotnetstandard-stellar-hd-wallet

**Comment by MicicFilip** [comment]
@PegasusWallet Could you be kind and share the source where you translate BIP32 seeds to a valid Stellar KeyPair? Thanks in advance

**Comment by elucidsoft** [comment]
All source is on my GitHub

**Comment by MicicFilip** [comment]
Thank you @elucidsoft , but I was asking about @PegasusWallet source code.

**Comment by bartekn** [comment]
Closed in #148.
