### ISSUE TITLE
getting date of issued payment

### ISSUE THREAD

**Issue by berlinguyinca** [stellar/java-stellar-sdk#77]
Dear all,

I'm trying to figure out how to get the actual date, when a payment has been made to an account. Using the PaymentOperationResponse, I can't seem to find out how todo this. Do you have any pointers for this?

thanks!

**Comment by bartekn** [comment]
This will be added when https://github.com/stellar/java-stellar-sdk/pull/71 is merged.

Right now you have to get a transaction where this operation was added and it should contain `created_at` field.

**Comment by berlinguyinca** [comment]
thanks and appreciate this. Is there a timeline when this happens? We hope to add this in time for the Build Challenge deadline.

**Comment by bartekn** [comment]
Hopefully Monday.
