### ISSUE TITLE
OperationResponse add created_at and transaction_hash

### ISSUE THREAD

**Issue by marusasa** [stellar/java-stellar-sdk#78]
I think it will be nice to have created_at and transaction_hash available in OperationResponse object.
Currently in order to get the timestamp of the operation I will have to make another request to the server to obtain the transaction object (TransactionResponse) which has the timestamp available.
But it looks like each operation already have these two information as part of it, so I think it makes sense.

Thank you,

**Comment by bartekn** [comment]
Added in https://github.com/stellar/java-stellar-sdk/pull/71. Merging on Monday.
