### ISSUE TITLE
Possible to Access Data Element?

### ISSUE THREAD

**Issue by markjohnson008** [stellar/java-stellar-sdk#80]
Is it possible to use the java sdk to access the data elements of an account?  I don't see it in AccountResponse, is there somewhere else it appears?

**Comment by berlinguyinca** [comment]
yes we are wondering about the same. Do you have any update for us at this stage?

**Comment by berlinguyinca** [comment]
I created a fork and have a rudimentary working version of it:

https://github.com/berlinguyinca/java-stellar-sdk

I will test it a bit later tomorrow on the test net, etc

**Comment by bartekn** [comment]
@berlinguyinca would you mind creating a PR with your changes?

**Comment by berlinguyinca** [comment]
not at all. will do so later tonight.

g.

**Comment by tamirms** [comment]
looks like this was fixed in https://github.com/stellar/java-stellar-sdk/commit/13e667b2263e3fcb97b266e842cc90a6eee6f709
