### ISSUE TITLE
How to freeze someone's account? 

### ISSUE THREAD

**Issue by jonasess** [stellar/java-stellar-sdk#83]
hello . i read the guide here https://www.stellar.org/developers/guides/issuing-assets.html
the part of Requiring or Revoking Authorization
there's a code source example in java . to set Revoking Authorization true . so i did it . but i was searching and reading in all the guide how to freeze someones account from using your asset , but still i couldn't find it .
could please help me . i couldn't find the method which you give a specific id account to freeze the asset .
thanks a lot

**Comment by jonasess** [comment]
.?

**Comment by bartekn** [comment]
Please ask question in our [Stack Exchange](https://stellar.stackexchange.com/).

In short, you have to use [`allow_trust`](https://www.stellar.org/developers/guides/concepts/list-of-operations.html#allow-trust) operation.

**Comment by jonasess** [comment]
thank you
