### ISSUE TITLE
Can't activate test account

### ISSUE THREAD

**Issue by eschgi** [stellar/java-stellar-sdk#84]
Hello,

i want to activate a stellar test account with the friendbot, but actually this not works:

I activate the test account with a http get request:
* https://horizon-testnet.stellar.org/friendbot?addr=GDFOFAUORGQ63LSU7ET57JRW7SS4IYWEQILKWCKBDFSUPLBFHA7TK5RZ

But i get following error:

```
{
  "type": "https://stellar.org/horizon-errors/https://stellar.org/horizon-errors/transaction_failed",
  "title": "Transaction Failed",
  "status": 400,
  "detail": "The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://www.stellar.org/developers/learn/concepts/list-of-operations.html",
  "extras": {
    "envelope_xdr": "AAAAABB90WssODNIgi6BHveqzxTRmIpvAFRyVNM+Hm2GVuCcAAAAZABiwhcAAI2IAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAyuKCjomh7a5U+Sffpjb8pcRixIIWqwlBGWVHrCU4PzUAAAAXSHboAAAAAAAAAAABhlbgnAAAAEBen8ATTJdwze/Ush5k1IJqMqeQ9vTenrEj9Qbc9bl+RBjjoRYuRntHUDsgJvNSn471v020+Zy7ltx+890C12oK",
    "result_codes": {
      "transaction": "tx_bad_seq"
    },
    "result_xdr": "AAAAAAAAAAD////7AAAAAA=="
  }
}
```

Can someone help me?

Kind regards
eschgi

**Comment by bartekn** [comment]
Check this: https://github.com/stellar/horizon/issues/427

**Comment by rolivieri** [comment]
@bartekn I am getting the exact same error that @eschgi described above. I am following the instructions on this [page](https://www.stellar.org/developers/guides/get-started/create-account.html).

Clicking on the link you shared above takes me to a page not found error on github.

Can you provide some guidance?
