### ISSUE TITLE
question: find all transactions since date X

### ISSUE THREAD

**Issue by berlinguyinca** [stellar/java-stellar-sdk#87]
hello,

is there a simple way to track all transactions, since date X. I know I can scan the blockchain with pagination or the stream api. But sadly just with a token. I'm more interested to get all transactions between 2 date points, if this is possible?

**Comment by bartekn** [comment]
There are plans to implement this in Horizon server. As of now, the fastest way would be to do a binary search using `/ledgers/{sequence}` endpoint. Caching should speed it up.
